% Lily was here -- automatically converted by c:/Program Files (x86)/LilyPond/usr/bin/midi2ly.py from output/midi/dh015fv.mid
\version "2.14.0"

\layout {
  \context {
    \Voice
    \remove "Note_heads_engraver"
    \consists "Completion_heads_engraver"
    \remove "Rest_engraver"
    \consists "Completion_rest_engraver"
  }
}

trackAchannelA = {


  \key c \major
    
  \time 4/4 
  

  \key c \major
  
  \tempo 4 = 109 
  
  % [MARKER] hasd005
  
  % [MARKER] Generated by NoteWorthy Composer
  
}

trackA = <<
  \context Voice = voiceA \trackAchannelA
>>


trackBchannelA = {
  
  \set Staff.instrumentName = "Soprano"
  
}

trackBchannelB = \relative c {
  \voiceOne
  g''4*160/192 r4*32/192 g4*160/192 r4*32/192 g4*160/192 r4*32/192 a4*160/192 
  r4*32/192 
  | % 2
  b4*160/192 r4*32/192 c16*7 r16 e,4*392/192 r4*184/192 e4*160/192 
  r4*32/192 f4*160/192 r4*32/192 
  | % 4
  g4*160/192 r4*32/192 e16*11 r16 
  | % 5
  g4*160/192 r4*32/192 g4*160/192 r4*32/192 g4*160/192 r4*32/192 a4*160/192 
  r4*32/192 
  | % 6
  b4*160/192 r4*32/192 c4*160/192 r4*32/192 c4*160/192 r4*32/192 b4*160/192 
  r4*32/192 
  | % 7
  a4*160/192 r4*32/192 g4*160/192 r4*32/192 g4*160/192 r4*32/192 b4*160/192 
  r4*32/192 
  | % 8
  a4*160/192 r4*32/192 g16*11 r16 
  | % 9
  g4*160/192 r4*32/192 c4*160/192 r4*32/192 c4*160/192 r4*32/192 g4*160/192 
  r4*32/192 
  | % 10
  g4*160/192 r4*32/192 e4*160/192 r4*32/192 g4*160/192 r4*32/192 c4*160/192 
  r4*32/192 
  | % 11
  g4*160/192 r4*32/192 a16*7 r16 d16*7 r16 d16*7 r16 c4*160/192 
  r4*32/192 
  | % 13
  b4*160/192 r4*32/192 c16*11 
}

trackBchannelBvoiceB = \relative c {
  \voiceTwo
  r4*9 d'4*160/192 
}

trackB = <<
  \context Voice = voiceA \trackBchannelA
  \context Voice = voiceB \trackBchannelB
  \context Voice = voiceC \trackBchannelBvoiceB
>>


trackCchannelA = {
  
  \set Staff.instrumentName = "Alto"
  
}

trackCchannelB = \relative c {
  \voiceOne
  e' r4*32/192 e4*160/192 r4*32/192 e4*160/192 r4*32/192 f4*160/192 
  r4*32/192 
  | % 2
  f4*160/192 r4*32/192 e16*7 r16 c4*392/192 r4*184/192 c4*160/192 
  r4*32/192 d4*160/192 r4*32/192 
  | % 4
  b4*160/192 r4*32/192 c16*11 r16 
  | % 5
  e4*160/192 r4*32/192 e4*160/192 r4*32/192 e4*160/192 r4*32/192 f4*160/192 
  r4*32/192 
  | % 6
  f4*160/192 r4*32/192 e4*160/192 r4*32/192 e4*160/192 r4*32/192 d4*160/192 
  r4*32/192 
  | % 7
  e4*160/192 r4*32/192 d4*160/192 r4*32/192 d4*160/192 r4*32/192 d4*160/192 
  r4*32/192 
  | % 8
  c4*160/192 r4*32/192 b16*11 r16 
  | % 9
  g'4*160/192 r4*32/192 e4*160/192 r4*32/192 e4*160/192 r4*32/192 e4*160/192 
  r4*32/192 
  | % 10
  e4*160/192 r4*32/192 c4*160/192 r4*32/192 e4*160/192 r4*32/192 e4*160/192 
  r4*32/192 
  | % 11
  g4*160/192 r4*32/192 f16*7 r16 f16*7 r16 f16*7 r16 e4*160/192 
  r4*32/192 
  | % 13
  d4*160/192 r4*32/192 e16*11 
}

trackCchannelBvoiceB = \relative c {
  \voiceTwo
  r4*9 b'4*160/192 
}

trackC = <<
  \context Voice = voiceA \trackCchannelA
  \context Voice = voiceB \trackCchannelB
  \context Voice = voiceC \trackCchannelBvoiceB
>>


trackDchannelA = {
  
  \set Staff.instrumentName = "Tenor"
  
}

trackDchannelB = \relative c {
  c' r4*32/192 c4*160/192 r4*32/192 c4*160/192 r4*32/192 c4*160/192 
  r4*32/192 
  | % 2
  g4*160/192 r4*32/192 g16*7 r16 g2 g4*160/192 r4*32/192 g4*160/192 
  r4*32/192 g4*160/192 r4*32/192 
  | % 4
  g4*160/192 r4*32/192 g16*11 r16 
  | % 5
  c4*160/192 r4*32/192 c4*160/192 r4*32/192 c4*160/192 r4*32/192 c4*160/192 
  r4*32/192 
  | % 6
  g4*160/192 r4*32/192 g4*160/192 r4*32/192 g4*160/192 r4*32/192 g4*160/192 
  r4*32/192 
  | % 7
  c4*160/192 r4*32/192 b4*160/192 r4*32/192 b4*160/192 r4*32/192 g4*160/192 
  r4*32/192 
  | % 8
  fis4*160/192 r4*32/192 g16*11 r16 
  | % 9
  g4*160/192 r4*32/192 g4*160/192 r4*32/192 g4*160/192 r4*32/192 c4*160/192 
  r4*32/192 
  | % 10
  c4*160/192 r4*32/192 g4*160/192 r4*32/192 g4*160/192 r4*32/192 g4*160/192 
  r4*32/192 
  | % 11
  c4*160/192 r4*32/192 c16*7 r16 a16*7 r16 g16*7 r16 g16*7 r16 g16*11 
}

trackD = <<

  \clef bass
  
  \context Voice = voiceA \trackDchannelA
  \context Voice = voiceB \trackDchannelB
>>


trackEchannelA = {
  
  \set Staff.instrumentName = "Bass"
  
}

trackEchannelB = \relative c {
  c4*160/192 r4*32/192 c4*160/192 r4*32/192 c4*160/192 r4*32/192 c4*160/192 
  r4*32/192 
  | % 2
  c4*160/192 r4*32/192 c16*7 r16 c2 g4*160/192 r4*32/192 g4*160/192 
  r4*32/192 g4*160/192 r4*32/192 
  | % 4
  g4*160/192 r4*32/192 c16*11 r16 
  | % 5
  c4*160/192 r4*32/192 c4*160/192 r4*32/192 c4*160/192 r4*32/192 c4*160/192 
  r4*32/192 
  | % 6
  c4*160/192 r4*32/192 c4*160/192 r4*32/192 c4*160/192 r4*32/192 g'4*160/192 
  r4*32/192 
  | % 7
  c,4*160/192 r4*32/192 d4*160/192 r4*32/192 d4*160/192 r4*32/192 d4*160/192 
  r4*32/192 
  | % 8
  d4*160/192 r4*32/192 g16*11 r16 
  | % 9
  g4*160/192 r4*32/192 c,4*160/192 r4*32/192 c4*160/192 r4*32/192 c4*160/192 
  r4*32/192 
  | % 10
  c4*160/192 r4*32/192 c4*160/192 r4*32/192 c4*160/192 r4*32/192 c4*160/192 
  r4*32/192 
  | % 11
  e4*160/192 r4*32/192 f16*7 r16 d16*7 r16 g16*7 r16 g,16*7 r16 c16*11 
}

trackE = <<

  \clef bass
  
  \context Voice = voiceA \trackEchannelA
  \context Voice = voiceB \trackEchannelB
>>


trackF = <<
>>


trackGchannelA = {
  
  \set Staff.instrumentName = "Digital Hymn #15"
  
}

trackG = <<
  \context Voice = voiceA \trackGchannelA
>>


trackHchannelA = {
  
  \set Staff.instrumentName = "My Maker and My King"
  
}

trackH = <<
  \context Voice = voiceA \trackHchannelA
>>


\score {
  <<
    \context Staff=trackB \trackA
    \context Staff=trackB \trackB
    \context Staff=trackC \trackA
    \context Staff=trackC \trackC
    \context Staff=trackD \trackA
    \context Staff=trackD \trackD
    \context Staff=trackE \trackA
    \context Staff=trackE \trackE
  >>
  \layout {}
  \midi {}
}
