% Lily was here -- automatically converted by c:/Program Files (x86)/LilyPond/usr/bin/midi2ly.py from output/midi/dh048fv.mid
\version "2.14.0"

\layout {
  \context {
    \Voice
    \remove "Note_heads_engraver"
    \consists "Completion_heads_engraver"
    \remove "Rest_engraver"
    \consists "Completion_rest_engraver"
  }
}

trackAchannelA = {


  \key ees \major
    
  \time 2/4 
  

  \key ees \major
  
  \tempo 4 = 100 
  
  % [MARKER] hasd029(1)
  
  % [MARKER] By Carl Maria von Weber (1786-1826)
  
  % [MARKER] Public  domain
  
  % [MARKER] Generated by NoteWorthy Composer
  \skip 4 
  \tempo 4 = 80 
  
}

trackA = <<
  \context Voice = voiceA \trackAchannelA
>>


trackBchannelA = {
  
  \set Staff.instrumentName = "Soprano"
  
}

trackBchannelB = \relative c {
  r4 g''4*160/192 r4*32/192 
  | % 2
  f4*160/192 r4*32/192 aes4*160/192 r4*32/192 
  | % 3
  g4*160/192 r4*32/192 c4*160/192 r4*32/192 
  | % 4
  bes4*94/192 r4*2/192 g4*94/192 r4*2/192 f16*7 r16 g4*160/192 
  r4*32/192 
  | % 6
  g4*160/192 r4*32/192 g4*160/192 r4*32/192 
  | % 7
  g4*160/192 r4*32/192 aes4*160/192 r4*32/192 
  | % 8
  d,4*160/192 r4*32/192 ees16*7 r16 g4*160/192 r4*32/192 
  | % 10
  f4*160/192 r4*32/192 aes4*160/192 r4*32/192 
  | % 11
  g4*160/192 r4*32/192 c4*160/192 r4*32/192 
  | % 12
  bes4*94/192 r4*2/192 g4*94/192 r4*2/192 f16*7 r16 g4*160/192 
  r4*32/192 
  | % 14
  bes4*160/192 r4*32/192 bes4*94/192 r4*2/192 aes4*94/192 r4*2/192 
  | % 15
  g4*94/192 r4*2/192 f4*94/192 r4*2/192 ees4*160/192 r4*32/192 
  | % 16
  d4*160/192 r4*32/192 ees16*7 
}

trackB = <<
  \context Voice = voiceA \trackBchannelA
  \context Voice = voiceB \trackBchannelB
>>


trackCchannelA = {
  
  \set Staff.instrumentName = "Alto"
  
}

trackCchannelB = \relative c {
  r4 ees'4*160/192 r4*32/192 
  | % 2
  ees4*160/192 r4*32/192 ees4*160/192 r4*32/192 
  | % 3
  ees4*160/192 r4*32/192 ges4*160/192 r4*32/192 
  | % 4
  g4*94/192 r4*2/192 ees4*94/192 r4*2/192 d16*7 r16 ees4*160/192 
  r4*32/192 
  | % 6
  ees4*160/192 r4*32/192 d4*160/192 r4*32/192 
  | % 7
  des4*160/192 r4*32/192 c4*160/192 r4*32/192 
  | % 8
  bes4*160/192 r4*32/192 bes16*7 r16 ees4*160/192 r4*32/192 
  | % 10
  ees4*160/192 r4*32/192 ees4*160/192 r4*32/192 
  | % 11
  ees4*160/192 r4*32/192 ges4*160/192 r4*32/192 
  | % 12
  g4*94/192 r4*2/192 ees4*94/192 r4*2/192 d16*7 r16 ees4*160/192 
  r4*32/192 
  | % 14
  g4*160/192 r4*32/192 f4*160/192 r4*32/192 
  | % 15
  c4*160/192 r4*32/192 bes4*160/192 r4*32/192 
  | % 16
  bes4*160/192 r4*32/192 bes16*7 
}

trackC = <<
  \context Voice = voiceA \trackCchannelA
  \context Voice = voiceB \trackCchannelB
>>


trackDchannelA = {
  
  \set Staff.instrumentName = "Tenor"
  
}

trackDchannelB = \relative c {
  r4 bes'4*160/192 r4*32/192 
  | % 2
  aes4*160/192 r4*32/192 c4*160/192 r4*32/192 
  | % 3
  bes4*160/192 r4*32/192 a4*160/192 r4*32/192 
  | % 4
  bes4*160/192 r4*32/192 aes16*7 r16 g4*160/192 r4*32/192 
  | % 6
  c4*160/192 r4*32/192 b4*160/192 r4*32/192 
  | % 7
  bes4*160/192 r4*32/192 aes4*160/192 r4*32/192 
  | % 8
  aes4*160/192 r4*32/192 g16*7 r16 bes4*160/192 r4*32/192 
  | % 10
  aes4*160/192 r4*32/192 c4*160/192 r4*32/192 
  | % 11
  bes4*160/192 r4*32/192 a4*160/192 r4*32/192 
  | % 12
  bes4*160/192 r4*32/192 aes16*7 r16 g4*94/192 r4*2/192 bes4*94/192 
  r4*2/192 
  | % 14
  des4*160/192 r4*32/192 c4*160/192 r4*32/192 
  | % 15
  aes4*160/192 r4*32/192 g4*160/192 r4*32/192 
  | % 16
  f4*160/192 r4*32/192 g16*7 
}

trackD = <<

  \clef bass
  
  \context Voice = voiceA \trackDchannelA
  \context Voice = voiceB \trackDchannelB
>>


trackEchannelA = {
  
  \set Staff.instrumentName = "Bass"
  
}

trackEchannelB = \relative c {
  r4 ees4*160/192 r4*32/192 
  | % 2
  ees4*160/192 r4*32/192 ees4*160/192 r4*32/192 
  | % 3
  ees4*160/192 r4*32/192 ees4*160/192 r4*32/192 
  | % 4
  ees4*160/192 r4*32/192 bes16*7 r16 ees4*160/192 r4*32/192 
  | % 6
  c4*160/192 r4*32/192 g4*160/192 r4*32/192 
  | % 7
  e'4*160/192 r4*32/192 f4*160/192 r4*32/192 
  | % 8
  bes,4*160/192 r4*32/192 ees16*7 r16 ees4*160/192 r4*32/192 
  | % 10
  ees4*160/192 r4*32/192 ees4*160/192 r4*32/192 
  | % 11
  ees4*160/192 r4*32/192 ees4*160/192 r4*32/192 
  | % 12
  ees4*160/192 r4*32/192 bes16*7 r16 ees4*160/192 r4*32/192 
  | % 14
  e4*160/192 r4*32/192 f4*160/192 r4*32/192 
  | % 15
  aes,4*160/192 r4*32/192 bes4*160/192 r4*32/192 
  | % 16
  bes4*160/192 r4*32/192 ees16*7 
}

trackE = <<

  \clef bass
  
  \context Voice = voiceA \trackEchannelA
  \context Voice = voiceB \trackEchannelB
>>


trackF = <<
>>


trackGchannelA = {
  
  \set Staff.instrumentName = "Digital Hymn #48"
  
}

trackG = <<
  \context Voice = voiceA \trackGchannelA
>>


trackHchannelA = {
  
  \set Staff.instrumentName = "Softly Now the Light of Day"
  
}

trackH = <<
  \context Voice = voiceA \trackHchannelA
>>


\score {
  <<
    \context Staff=trackB \trackA
    \context Staff=trackB \trackB
    \context Staff=trackC \trackA
    \context Staff=trackC \trackC
    \context Staff=trackD \trackA
    \context Staff=trackD \trackD
    \context Staff=trackE \trackA
    \context Staff=trackE \trackE
  >>
  \layout {}
  \midi {}
}
