% Lily was here -- automatically converted by c:/Program Files (x86)/LilyPond/usr/bin/midi2ly.py from output/midi/dh096fv.mid
\version "2.14.0"

\layout {
  \context {
    \Voice
    \remove "Note_heads_engraver"
    \consists "Completion_heads_engraver"
    \remove "Rest_engraver"
    \consists "Completion_rest_engraver"
  }
}

trackAchannelA = {


  \key g \major
    
  \time 2/2 
  

  \key g \major
  
  \tempo 4 = 100 
  
  % [MARKER] Quartet Template
  
  % [MARKER] By <Name>
  
  % [MARKER] Copyright ~ <Year> by <Name>
  
  % [MARKER] All Rights Reserved
  
  % [MARKER] Generated by NoteWorthy Composer
  \skip 2 
  \tempo 4 = 160 
  \skip 1*15 
  \tempo 4 = 140 
  \skip 1 
  \tempo 4 = 160 
  \skip 1*14 
  \tempo 4 = 150 
  \skip 4 
  \tempo 4 = 140 
  \skip 2 
  \tempo 4 = 130 
  \skip 2 
  \tempo 4 = 120 
  
}

trackA = <<
  \context Voice = voiceA \trackAchannelA
>>


trackBchannelA = {
  
  \set Staff.instrumentName = "Soprano"
  
}

trackBchannelB = \relative c {
  r2 d'4*160/192 r4*32/192 g16*11 r16 g4*160/192 r4*32/192 a16*11 
  r16 a4*160/192 r4*32/192 b4*160/192 r4*32/192 
  | % 4
  g4*160/192 r4*32/192 e4*160/192 r4*32/192 a4*160/192 r4*32/192 g16*7 
  r16 fis4*160/192 r4*32/192 d4*94/192 r4*2/192 e4*94/192 r4*2/192 fis4*160/192 
  r4*32/192 
  | % 6
  g4*160/192 r4*32/192 a4*160/192 r4*32/192 b4*160/192 r4*32/192 c16*11 
  r16 b4*160/192 r4*32/192 b4*160/192 r4*32/192 
  | % 8
  a4*160/192 r4*32/192 a4*160/192 r4*32/192 g4*160/192 r4*32/192 g16*7 
  r16 fis4*160/192 r4*32/192 d4*160/192 r4*32/192 g16*11 r16 g4*160/192 
  r4*32/192 a16*11 r16 a4*160/192 r4*32/192 b4*160/192 r4*32/192 
  | % 12
  g4*160/192 r4*32/192 e4*160/192 r4*32/192 a4*160/192 r4*32/192 g16*7 
  r16 fis4*160/192 r4*32/192 d4*94/192 r4*2/192 e4*94/192 r4*2/192 fis4*160/192 
  r4*32/192 
  | % 14
  g4*160/192 r4*32/192 a4*160/192 r4*32/192 b4*160/192 r4*32/192 c16*11 
  r16 b4*160/192 r4*32/192 b4*160/192 r4*32/192 
  | % 16
  a4*160/192 r4*32/192 g4*160/192 r4*32/192 fis4*160/192 r4*32/192 g16*11 
  r16 d4*160/192 r4*32/192 d16*11 r16 d4*160/192 r4*32/192 g16*11 
  r16 g4*160/192 r4*32/192 a16*11 r16 a4*160/192 r4*32/192 b16*11 
  r16 a4*160/192 r4*32/192 b4*160/192 r4*32/192 
  | % 22
  c4*160/192 r4*32/192 d4*160/192 r4*32/192 b4*160/192 r4*32/192 a4*160/192 
  r4*32/192 
  | % 23
  b4*160/192 r4*32/192 c4*160/192 r4*32/192 a4*160/192 r4*32/192 b4*160/192 
  r4*32/192 
  | % 24
  c4*160/192 r4*32/192 d4*160/192 r4*32/192 b4*160/192 r4*32/192 a16*11 
  r16 d,4*160/192 r4*32/192 d16*11 r16 d4*160/192 r4*32/192 g16*11 
  r16 g4*160/192 r4*32/192 a16*11 r16 a4*160/192 r4*32/192 b16*11 
  r16 a4*160/192 r4*32/192 b4*160/192 r4*32/192 
  | % 30
  c4*160/192 r4*32/192 d4*160/192 r4*32/192 b4*160/192 r4*32/192 a4*160/192 
  r4*32/192 
  | % 31
  b4*160/192 r4*32/192 c4*160/192 r4*32/192 a4*160/192 r4*32/192 g16*7 
  r16 fis16*7 r16 g16*11 
}

trackB = <<
  \context Voice = voiceA \trackBchannelA
  \context Voice = voiceB \trackBchannelB
>>


trackCchannelA = {
  
  \set Staff.instrumentName = "Alto"
  
}

trackCchannelB = \relative c {
  r2 d'4*160/192 r4*32/192 b16*11 r16 d4*160/192 r4*32/192 d16*11 
  r16 d4*160/192 r4*32/192 d16*7 r16 e16*7 r16 d16*11 r16 d4*160/192 
  r4*32/192 d16*7 r16 d16*7 r16 d16*7 r16 d16*7 r16 e16*7 r16 e16*7 
  r16 d16*11 r16 d4*160/192 r4*32/192 b16*11 r16 d4*160/192 r4*32/192 d16*11 
  r16 d4*160/192 r4*32/192 d16*7 r16 e16*7 r16 d16*11 r16 d4*160/192 
  r4*32/192 d16*7 r16 d16*7 r16 d16*7 r16 d16*7 r16 e16*7 r16 d4 
  c4*160/192 r4*32/192 b16*11 r16 d4*160/192 r4*32/192 d16*11 r16 d4*160/192 
  r4*32/192 d16*11 r16 d4*160/192 r4*32/192 d16*11 r16 d4*160/192 
  r4*32/192 d16*11 r16 d4*160/192 r4*32/192 d16*11 r16 d4*160/192 
  r4*32/192 d16*11 r16 d4*160/192 r4*32/192 d16*11 r16 d4*160/192 
  r4*32/192 d16*11 r16 d4*160/192 r4*32/192 d16*11 r16 d4*160/192 
  r4*32/192 d4 
  | % 27
  c d4*160/192 r4*32/192 b4*160/192 r4*32/192 d16*11 r16 d4*160/192 
  r4*32/192 d16*11 r16 d4*160/192 r4*32/192 d16*11 r16 d4*160/192 
  r4*32/192 e4 
  | % 31
  d c4*160/192 r4*32/192 e4*160/192 r4*32/192 d16*7 r16 c16*7 
  r16 b16*11 
}

trackC = <<
  \context Voice = voiceA \trackCchannelA
  \context Voice = voiceB \trackCchannelB
>>


trackDchannelA = {
  
  \set Staff.instrumentName = "Tenor"
  
}

trackDchannelB = \relative c {
  r2 d4*160/192 r4*32/192 d16*11 r16 g4*160/192 r4*32/192 fis16*11 
  r16 fis4*160/192 r4*32/192 g16*7 r16 g4*160/192 r4*32/192 c4*160/192 
  r4*32/192 b16*7 r16 a4*160/192 r4*32/192 fis4*94/192 r4*2/192 g4*94/192 
  r4*2/192 a4*160/192 r4*32/192 
  | % 6
  g4*160/192 r4*32/192 fis4*160/192 r4*32/192 g4*160/192 r4*32/192 a16*7 
  r16 g16*7 r16 e16*7 r16 e4*160/192 r4*32/192 a4*160/192 r4*32/192 a16*11 
  r16 d,4*160/192 r4*32/192 d16*11 r16 g4*160/192 r4*32/192 fis16*11 
  r16 fis4*160/192 r4*32/192 g16*7 r16 g4*160/192 r4*32/192 c4*160/192 
  r4*32/192 b16*7 r16 a4*160/192 r4*32/192 fis4*94/192 r4*2/192 g4*94/192 
  r4*2/192 a4*160/192 r4*32/192 
  | % 14
  g4*160/192 r4*32/192 fis4*160/192 r4*32/192 g4*160/192 r4*32/192 a16*7 
  r16 g16*7 r16 g4*160/192 r4*32/192 
  | % 16
  c4*160/192 r4*32/192 b4*160/192 r4*32/192 a4*160/192 r4*32/192 g16*11 
  r16 d4*160/192 r4*32/192 d16*11 r16 d4*160/192 r4*32/192 d16*11 
  r16 g4*160/192 r4*32/192 fis16*11 r16 fis4*160/192 r4*32/192 g16*11 
  r16 fis4*160/192 r4*32/192 g4*160/192 r4*32/192 
  | % 22
  a4*160/192 r4*32/192 b4*160/192 r4*32/192 g4*160/192 r4*32/192 fis4*160/192 
  r4*32/192 
  | % 23
  g4*160/192 r4*32/192 a4*160/192 r4*32/192 fis4*160/192 r4*32/192 g4*160/192 
  r4*32/192 
  | % 24
  a4*160/192 r4*32/192 b4*160/192 r4*32/192 g4*160/192 r4*32/192 fis16*11 
  r16 fis4*160/192 r4*32/192 fis16*11 r16 fis4*160/192 r4*32/192 g16*11 
  r16 g4*160/192 r4*32/192 fis4*160/192 r4*32/192 
  | % 28
  g4*160/192 r4*32/192 a4*160/192 r4*32/192 fis4*160/192 r4*32/192 g16*11 
  r16 fis4*160/192 r4*32/192 g16*11 r16 g4*160/192 r4*32/192 e4*160/192 
  r4*32/192 
  | % 31
  gis4*160/192 r4*32/192 a4*160/192 r4*32/192 a4*160/192 r4*32/192 b16*7 
  r16 a16*7 r16 g16*11 
}

trackD = <<

  \clef bass
  
  \context Voice = voiceA \trackDchannelA
  \context Voice = voiceB \trackDchannelB
>>


trackEchannelA = {
  
  \set Staff.instrumentName = "Bass"
  
}

trackEchannelB = \relative c {
  r2 d4*160/192 r4*32/192 g,16*11 r16 b4*160/192 r4*32/192 d16*11 
  r16 d4*160/192 r4*32/192 g4*160/192 r4*32/192 
  | % 4
  b,4*160/192 r4*32/192 c4*160/192 r4*32/192 a4*160/192 r4*32/192 d16*11 
  r16 d4*160/192 r4*32/192 c4*160/192 r4*32/192 
  | % 6
  b4*160/192 r4*32/192 a4*160/192 r4*32/192 g4*160/192 r4*32/192 fis16*7 
  r16 g16*7 r16 c16*7 r16 cis16*7 r16 d16*11 r16 d4*160/192 r4*32/192 g,16*11 
  r16 b4*160/192 r4*32/192 d16*11 r16 d4*160/192 r4*32/192 g4*160/192 
  r4*32/192 
  | % 12
  b,4*160/192 r4*32/192 c4*160/192 r4*32/192 a4*160/192 r4*32/192 d16*11 
  r16 d4*160/192 r4*32/192 c4*160/192 r4*32/192 
  | % 14
  b4*160/192 r4*32/192 a4*160/192 r4*32/192 g4*160/192 r4*32/192 fis16*7 
  r16 g16*7 r16 c16*7 r16 d16*7 r16 g,16*11 r16 d'4*160/192 r4*32/192 d16*11 
  r16 d4*160/192 r4*32/192 b16*11 r16 b4*160/192 r4*32/192 d16*11 
  r16 d4*160/192 r4*32/192 g16*11 r16 d4*160/192 r4*32/192 d16*11 
  r16 d4*160/192 r4*32/192 d16*11 r16 d4*160/192 r4*32/192 d16*11 
  r16 d4*160/192 r4*32/192 d16*11 r16 d4*160/192 r4*32/192 d4*160/192 
  r4*32/192 
  | % 26
  e4*160/192 r4*32/192 d4*160/192 r4*32/192 c4*160/192 r4*32/192 b4*160/192 
  r4*32/192 
  | % 27
  a4*160/192 r4*32/192 b4*160/192 r4*32/192 g4*160/192 r4*32/192 d'4*160/192 
  r4*32/192 
  | % 28
  e4*160/192 r4*32/192 fis4*160/192 r4*32/192 d4*160/192 r4*32/192 g16*11 
  r16 d4*160/192 r4*32/192 g,4*160/192 r4*32/192 
  | % 30
  a4*160/192 r4*32/192 b4*160/192 r4*32/192 g4*160/192 r4*32/192 e'4*160/192 
  r4*32/192 
  | % 31
  b4*160/192 r4*32/192 a4*160/192 r4*32/192 c4*160/192 r4*32/192 d16*7 
  r16 d16*7 r16 g,16*11 
}

trackE = <<

  \clef bass
  
  \context Voice = voiceA \trackEchannelA
  \context Voice = voiceB \trackEchannelB
>>


trackF = <<
>>


trackGchannelA = {
  
  \set Staff.instrumentName = "Digital Hymn #96"
  
}

trackG = <<
  \context Voice = voiceA \trackGchannelA
>>


trackHchannelA = {
  
  \set Staff.instrumentName = "The Spacious Firmament"
  
}

trackH = <<
  \context Voice = voiceA \trackHchannelA
>>


\score {
  <<
    \context Staff=trackB \trackA
    \context Staff=trackB \trackB
    \context Staff=trackC \trackA
    \context Staff=trackC \trackC
    \context Staff=trackD \trackA
    \context Staff=trackD \trackD
    \context Staff=trackE \trackA
    \context Staff=trackE \trackE
  >>
  \layout {}
  \midi {}
}
