% Lily was here -- automatically converted by c:/Program Files (x86)/LilyPond/usr/bin/midi2ly.py from output/midi/dh595fv.mid
\version "2.14.0"

\layout {
  \context {
    \Voice
    \remove "Note_heads_engraver"
    \consists "Completion_heads_engraver"
    \remove "Rest_engraver"
    \consists "Completion_rest_engraver"
  }
}

trackAchannelA = {


  \key ees \major
    
  \time 6/4 
  

  \key ees \major
  
  \tempo 4 = 130 
  
  % [MARKER] Quartet Template
  
  % [MARKER] By <Name>
  
  % [MARKER] Copyright ~ <Year> by <Name>
  
  % [MARKER] All Rights Reserved
  
  % [MARKER] Generated by NoteWorthy Composer
  \skip 2*31 
  \tempo 4 = 130 
  \skip 4*64/192 
  \tempo 4 = 129 
  \skip 4*64/192 
  \tempo 4 = 128 
  \skip 4*64/192 
  \tempo 4 = 126 
  \skip 4*64/192 
  \tempo 4 = 126 
  \skip 4*64/192 
  \tempo 4 = 125 
  \skip 4*64/192 
  \tempo 4 = 123 
  \skip 4*64/192 
  \tempo 4 = 122 
  \skip 4*64/192 
  \tempo 4 = 122 
  \skip 4*64/192 
  \tempo 4 = 120 
  \skip 4*64/192 
  \tempo 4 = 120 
  \skip 4*64/192 
  \tempo 4 = 118 
  \skip 4*64/192 
  | % 12
  
  \tempo 4 = 117 
  \skip 4*64/192 
  \tempo 4 = 116 
  \skip 4*64/192 
  \tempo 4 = 116 
  \skip 4*64/192 
  \tempo 4 = 115 
  \skip 4*64/192 
  \tempo 4 = 113 
  \skip 4*64/192 
  \tempo 4 = 113 
  \skip 4*64/192 
  \tempo 4 = 112 
  \skip 64. 
  \tempo 4 = 110 
  \skip 64. 
  \tempo 4 = 109 
  \skip 64. 
  \tempo 4 = 108 
  \skip 4*19/192 
  \tempo 4 = 107 
  \skip 64. 
  \tempo 4 = 106 
  \skip 64. 
  \tempo 4 = 105 
  \skip 4*19/192 
  \tempo 4 = 104 
  \skip 64. 
  \tempo 4 = 104 
  \skip 64. 
  \tempo 4 = 103 
  \skip 64. 
  \tempo 4 = 102 
  \skip 4*19/192 
  \tempo 4 = 101 
  \skip 64. 
  \tempo 4 = 100 
  \skip 64. 
  \tempo 4 = 98 
  \skip 4*19/192 
  \tempo 4 = 97 
  \skip 64. 
  \tempo 4 = 96 
  \skip 64. 
  \tempo 4 = 96 
  \skip 64. 
  \tempo 4 = 94 
  \skip 4*19/192 
  \tempo 4 = 93 
  \skip 64. 
  \tempo 4 = 93 
  \skip 64. 
  \tempo 4 = 91 
  \skip 4*19/192 
  \tempo 4 = 90 
  \skip 64. 
  \tempo 4 = 89 
  \skip 64. 
  \tempo 4 = 89 
  \skip 64. 
  \tempo 4 = 88 
  \skip 4*19/192 
  \tempo 4 = 87 
  \skip 64. 
  \tempo 4 = 86 
  \skip 64. 
  \tempo 4 = 85 
  \skip 4*19/192 
  \tempo 4 = 83 
  \skip 64. 
  \tempo 4 = 82 
  \skip 64. 
  \tempo 4 = 82 
  \skip 64. 
  \tempo 4 = 80 
  \skip 4*19/192 
  \tempo 4 = 80 
  \skip 64. 
  \tempo 4 = 78 
  \skip 64. 
  \tempo 4 = 77 
  \skip 4*19/192 
  \tempo 4 = 76 
  \skip 64. 
  \tempo 4 = 75 
  \skip 64. 
  \tempo 4 = 75 
  \skip 64. 
  \tempo 4 = 73 
  \skip 4*19/192 
  \tempo 4 = 72 
  \skip 64. 
  \tempo 4 = 72 
  \skip 64. 
  \tempo 4 = 71 
  \skip 4*19/192 
  | % 13
  
  \tempo 4 = 69 
  \skip 4 
  \tempo 4 = 120 
  \skip 4 
  \tempo 4 = 130 
  \skip 4*11 
  \tempo 4 = 130 
  \skip 4*25/192 
  \tempo 4 = 129 
  \skip 4*26/192 
  \tempo 4 = 128 
  \skip 4*25/192 
  \tempo 4 = 126 
  \skip 4*26/192 
  \tempo 4 = 126 
  \skip 4*26/192 
  \tempo 4 = 125 
  \skip 4*25/192 
  \tempo 4 = 123 
  \skip 4*26/192 
  \tempo 4 = 122 
  \skip 4*25/192 
  \tempo 4 = 122 
  \skip 4*26/192 
  \tempo 4 = 120 
  \skip 4*26/192 
  \tempo 4 = 120 
  \skip 4*25/192 
  \tempo 4 = 118 
  \skip 4*26/192 
  \tempo 4 = 117 
  \skip 4*25/192 
  \tempo 4 = 116 
  \skip 4*26/192 
  \tempo 4 = 116 
  \skip 4*26/192 
  \tempo 4 = 115 
  \skip 4*25/192 
  \tempo 4 = 113 
  \skip 4*26/192 
  \tempo 4 = 113 
  \skip 4*25/192 
  \tempo 4 = 112 
  \skip 4*26/192 
  \tempo 4 = 110 
  \skip 4*26/192 
  \tempo 4 = 109 
  \skip 4*25/192 
  \tempo 4 = 108 
  \skip 4*26/192 
  \tempo 4 = 107 
  \skip 4*25/192 
  \tempo 4 = 106 
  \skip 4*26/192 
  \tempo 4 = 105 
  \skip 4*26/192 
  \tempo 4 = 104 
  \skip 4*25/192 
  \tempo 4 = 104 
  \skip 4*26/192 
  \tempo 4 = 103 
  \skip 4*25/192 
  \tempo 4 = 102 
  \skip 4*26/192 
  \tempo 4 = 101 
  \skip 4*26/192 
  \tempo 4 = 100 
  
}

trackA = <<
  \context Voice = voiceA \trackAchannelA
>>


trackBchannelA = {
  
  \set Staff.instrumentName = "Soprano"
  
}

trackBchannelB = \relative c {
  r4 g''4*160/192 r4*32/192 bes4*256/192 r4*32/192 c4*94/192 r4*2/192 bes4*160/192 
  r4*32/192 g16*7 r16 bes,4*160/192 r4*32/192 g'4*256/192 r4*32/192 aes4*94/192 
  r4*2/192 g4*160/192 r4*32/192 ees16*7 r16 g4*160/192 r4*32/192 f4*160/192 
  r4*32/192 g4*160/192 r4*32/192 aes4*160/192 r4*32/192 bes4*160/192 
  r4*32/192 
  | % 4
  bes4*160/192 r4*32/192 aes4*160/192 r4*32/192 g16*19 r16 g4*160/192 
  r4*32/192 bes4*256/192 r4*32/192 c4*94/192 r4*2/192 bes4*160/192 
  r4*32/192 g16*7 r16 bes,4*160/192 r4*32/192 g'4*256/192 r4*32/192 aes4*94/192 
  r4*2/192 g4*160/192 r4*32/192 ees16*7 r16 g4*160/192 r4*32/192 f4*160/192 
  r4*32/192 g4*160/192 r4*32/192 aes4*160/192 r4*32/192 g16*7 r16 f4*160/192 
  r4*32/192 ees16*19 r16 ees4*160/192 r4*32/192 c'4*256/192 r4*32/192 c4*94/192 
  r4*2/192 c4*160/192 r4*32/192 ees4*160/192 r4*32/192 
  | % 10
  d4*160/192 r4*32/192 c4*160/192 r4*32/192 bes4*256/192 r4*32/192 g4*94/192 
  r4*2/192 c4*160/192 r4*32/192 bes16*7 r16 bes4*160/192 r4*32/192 a4*256/192 
  r4*32/192 bes4*94/192 r4*2/192 c4*160/192 r4*32/192 ees4*160/192 
  r4*32/192 
  | % 12
  d4*160/192 r4*32/192 c4*160/192 r4*32/192 bes4*160/192 r4*32/192 bes4*160/192 
  r4*32/192 a4*160/192 r4*32/192 aes16*7 r16 g4*160/192 r4*32/192 bes4*256/192 
  r4*32/192 c4*94/192 r4*2/192 bes4*160/192 r4*32/192 g16*7 r16 bes,4*160/192 
  r4*32/192 g'4*256/192 r4*32/192 aes4*94/192 r4*2/192 g4*160/192 
  r4*32/192 ees16*7 r16 g4*160/192 r4*32/192 f4*160/192 r4*32/192 g4*160/192 
  r4*32/192 aes4*160/192 r4*32/192 g16*7 r16 f4*160/192 r4*32/192 ees16*19 
}

trackB = <<
  \context Voice = voiceA \trackBchannelA
  \context Voice = voiceB \trackBchannelB
>>


trackCchannelA = {
  
  \set Staff.instrumentName = "Alto"
  
}

trackCchannelB = \relative c {
  r4 ees'4*160/192 r4*32/192 g4*256/192 r4*32/192 aes4*94/192 r4*2/192 g4*160/192 
  r4*32/192 ees16*7 r16 bes4*160/192 r4*32/192 ees4*256/192 r4*32/192 ees4*94/192 
  r4*2/192 ees4*160/192 r4*32/192 bes16*7 r16 ees4*160/192 r4*32/192 d4*160/192 
  r4*32/192 d4*160/192 r4*32/192 d4*160/192 r4*32/192 d4*160/192 
  r4*32/192 
  | % 4
  d4*160/192 r4*32/192 d4*160/192 r4*32/192 ees16*19 r16 ees4*160/192 
  r4*32/192 g4*256/192 r4*32/192 aes4*94/192 r4*2/192 g4*160/192 
  r4*32/192 ees16*7 r16 bes4*160/192 r4*32/192 ees4*256/192 r4*32/192 ees4*94/192 
  r4*2/192 ees4*160/192 r4*32/192 bes16*7 r16 ees4*160/192 r4*32/192 d4*160/192 
  r4*32/192 d4*160/192 r4*32/192 d4*160/192 r4*32/192 d16*7 r16 d4*160/192 
  r4*32/192 bes16*19 r16 ees4*160/192 r4*32/192 aes4*256/192 r4*32/192 aes4*94/192 
  r4*2/192 aes4*160/192 r4*32/192 c4*160/192 r4*32/192 
  | % 10
  bes4*160/192 r4*32/192 aes4*160/192 r4*32/192 g4*256/192 r4*32/192 ees4*94/192 
  r4*2/192 aes4*160/192 r4*32/192 g16*7 r16 ees4*160/192 r4*32/192 ees4*256/192 
  r4*32/192 ees4*94/192 r4*2/192 ees4*160/192 r4*32/192 g4*160/192 
  r4*32/192 
  | % 12
  f4*160/192 r4*32/192 ees4*160/192 r4*32/192 d4*160/192 r4*32/192 d4*160/192 
  r4*32/192 ees4*160/192 r4*32/192 f16*7 r16 ees4*160/192 r4*32/192 g4*256/192 
  r4*32/192 aes4*94/192 r4*2/192 g4*160/192 r4*32/192 ees16*7 r16 bes4*160/192 
  r4*32/192 ees4*256/192 r4*32/192 ees4*94/192 r4*2/192 ees4*160/192 
  r4*32/192 bes16*7 r16 ees4*160/192 r4*32/192 d4*160/192 r4*32/192 d4*160/192 
  r4*32/192 d4*160/192 r4*32/192 d16*7 r16 d4*160/192 r4*32/192 bes16*19 
}

trackC = <<
  \context Voice = voiceA \trackCchannelA
  \context Voice = voiceB \trackCchannelB
>>


trackDchannelA = {
  
  \set Staff.instrumentName = "Tenor"
  
}

trackDchannelB = \relative c {
  r4 bes'4*160/192 r4*32/192 ees4*256/192 r4*32/192 ees4*94/192 
  r4*2/192 ees4*160/192 r4*32/192 bes16*7 r16 g4*160/192 r4*32/192 bes4*256/192 
  r4*32/192 c4*94/192 r4*2/192 bes4*160/192 r4*32/192 g16*7 r16 bes4*160/192 
  r4*32/192 aes4*160/192 r4*32/192 g4*160/192 r4*32/192 f4*160/192 
  r4*32/192 f4*160/192 r4*32/192 
  | % 4
  f4*160/192 r4*32/192 c'4*160/192 r4*32/192 bes16*19 r16 bes4*160/192 
  r4*32/192 ees4*256/192 r4*32/192 ees4*94/192 r4*2/192 ees4*160/192 
  r4*32/192 bes16*7 r16 g4*160/192 r4*32/192 bes4*256/192 r4*32/192 c4*94/192 
  r4*2/192 bes4*160/192 r4*32/192 g16*7 r16 bes4*160/192 r4*32/192 aes4*160/192 
  r4*32/192 bes4*160/192 r4*32/192 c4*160/192 r4*32/192 bes16*7 
  r16 aes4*160/192 r4*32/192 g16*19 r16*5 aes,16*23 r16 ees'16*19 
  r16 bes'4*160/192 r4*32/192 c4*256/192 r4*32/192 bes4*94/192 
  r4*2/192 a4*160/192 r4*32/192 a4*160/192 r4*32/192 
  | % 12
  a4*160/192 r4*32/192 a4*160/192 r4*32/192 bes4*160/192 r4*32/192 bes4*160/192 
  r4*32/192 c4*160/192 r4*32/192 d16*7 r16 bes4*160/192 r4*32/192 ees4*256/192 
  r4*32/192 ees4*94/192 r4*2/192 ees4*160/192 r4*32/192 bes16*7 
  r16 g4*160/192 r4*32/192 bes4*256/192 r4*32/192 c4*94/192 r4*2/192 bes4*160/192 
  r4*32/192 g16*7 r16 bes4*160/192 r4*32/192 aes4*160/192 r4*32/192 bes4*160/192 
  r4*32/192 c4*160/192 r4*32/192 bes16*7 r16 aes4*160/192 r4*32/192 g16*19 
}

trackD = <<

  \clef bass
  
  \context Voice = voiceA \trackDchannelA
  \context Voice = voiceB \trackDchannelB
>>


trackEchannelA = {
  
  \set Staff.instrumentName = "Bass"
  
}

trackEchannelB = \relative c {
  r4 ees4*160/192 r4*32/192 ees4*256/192 r4*32/192 ees4*94/192 
  r4*2/192 ees4*160/192 r4*32/192 ees16*7 r16 ees4*160/192 r4*32/192 ees4*256/192 
  r4*32/192 ees4*94/192 r4*2/192 ees4*160/192 r4*32/192 ees16*7 
  r16 ees4*160/192 r4*32/192 bes4*160/192 r4*32/192 bes4*160/192 
  r4*32/192 bes4*160/192 r4*32/192 bes4*160/192 r4*32/192 
  | % 4
  bes4*160/192 r4*32/192 bes4*160/192 r4*32/192 ees16*19 r16 ees4*160/192 
  r4*32/192 ees4*256/192 r4*32/192 ees4*94/192 r4*2/192 ees4*160/192 
  r4*32/192 ees16*7 r16 ees4*160/192 r4*32/192 ees4*256/192 r4*32/192 ees4*94/192 
  r4*2/192 ees4*160/192 r4*32/192 ees16*7 r16 ees4*160/192 r4*32/192 bes4*160/192 
  r4*32/192 bes4*160/192 r4*32/192 bes4*160/192 r4*32/192 bes16*7 
  r16 bes4*160/192 r4*32/192 ees16*19 r16*5 aes,16*23 r16 ees'16*19 
  r16 g4*160/192 r4*32/192 f4*256/192 r4*32/192 f4*94/192 r4*2/192 f4*160/192 
  r4*32/192 f4*160/192 r4*32/192 
  | % 12
  <f f, >4*160/192 r4*32/192 <f f, >4*160/192 r4*32/192 <bes bes, >4*160/192 
  r4*32/192 <bes bes, >4*160/192 r4*32/192 <f f, >4*160/192 r4*32/192 <bes bes, >16*7 
  r16 ees,4*160/192 r4*32/192 ees4*256/192 r4*32/192 ees4*94/192 
  r4*2/192 ees4*160/192 r4*32/192 ees16*7 r16 ees4*160/192 r4*32/192 ees4*256/192 
  r4*32/192 ees4*94/192 r4*2/192 ees4*160/192 r4*32/192 ees16*7 
  r16 ees4*160/192 r4*32/192 bes4*160/192 r4*32/192 bes4*160/192 
  r4*32/192 bes4*160/192 r4*32/192 bes16*7 r16 bes4*160/192 r4*32/192 ees16*19 
}

trackE = <<

  \clef bass
  
  \context Voice = voiceA \trackEchannelA
  \context Voice = voiceB \trackEchannelB
>>


trackF = <<
>>


trackGchannelA = {
  
  \set Staff.instrumentName = "Digital Hymn #595"
  
}

trackG = <<
  \context Voice = voiceA \trackGchannelA
>>


trackHchannelA = {
  
  \set Staff.instrumentName = "Let Every Lamp Be Burning"
  
}

trackH = <<
  \context Voice = voiceA \trackHchannelA
>>


\score {
  <<
    \context Staff=trackB \trackA
    \context Staff=trackB \trackB
    \context Staff=trackC \trackA
    \context Staff=trackC \trackC
    \context Staff=trackD \trackA
    \context Staff=trackD \trackD
    \context Staff=trackE \trackA
    \context Staff=trackE \trackE
  >>
  \layout {}
  \midi {}
}
