% Lily was here -- automatically converted by c:/Program Files (x86)/LilyPond/usr/bin/midi2ly.py from output/midi/001-praise-to-the-lord.mid
\version "2.14.0"

\layout {
  \context {
    \Voice
    \remove "Note_heads_engraver"
    \consists "Completion_heads_engraver"
    \remove "Rest_engraver"
    \consists "Completion_rest_engraver"
  }
}

trackAchannelA = {


  \key f \major
    
  \time 3/4 
  

  \key f \major
  
  \tempo 4 = 100 
  
  % [MARKER] Praise to the Lord
  
  % [MARKER] Generated by NoteWorthy Composer
  
}

trackA = <<
  \context Voice = voiceA \trackAchannelA
>>


trackBchannelA = {
  
  \set Staff.instrumentName = "Soprano"
  
}

trackBchannelB = \relative c {
  f'4*160/192 r4*32/192 f4*160/192 r4*32/192 c'4*160/192 r4*32/192 
  | % 2
  a4*256/192 r4*32/192 g4*94/192 r4*2/192 f4*160/192 r4*32/192 
  | % 3
  e4*160/192 r4*32/192 d4*160/192 r4*32/192 c4*160/192 r4*32/192 
  | % 4
  d4*160/192 r4*32/192 e4*160/192 r4*32/192 f4*160/192 r4*32/192 
  | % 5
  g16*11 r16 
  | % 6
  f16*11 r16 
  | % 7
  f4*160/192 r4*32/192 f4*160/192 r4*32/192 c'4*160/192 r4*32/192 
  | % 8
  a4*256/192 r4*32/192 g4*94/192 r4*2/192 f4*160/192 r4*32/192 
  | % 9
  e4*160/192 r4*32/192 d4*160/192 r4*32/192 c4*160/192 r4*32/192 
  | % 10
  d4*160/192 r4*32/192 e4*160/192 r4*32/192 f4*160/192 r4*32/192 
  | % 11
  g16*11 r16 
  | % 12
  f16*11 r16 
  | % 13
  c'4*160/192 r4*32/192 c4*160/192 r4*32/192 c4*160/192 r4*32/192 
  | % 14
  d16*11 r16 
  | % 15
  a4*160/192 r4*32/192 bes4*160/192 r4*32/192 c4*160/192 r4*32/192 
  | % 16
  c4*160/192 r4*32/192 bes4*160/192 r4*32/192 a4*160/192 r4*32/192 
  | % 17
  g16*11 r16 
  | % 18
  c,4*160/192 r4*32/192 d4*160/192 r4*32/192 e4*160/192 r4*32/192 
  | % 19
  f4*160/192 r4*32/192 g4*160/192 r4*32/192 a4*160/192 r4*32/192 
  | % 20
  g16*11 r16 
  | % 21
  f16*11 
}

trackB = <<
  \context Voice = voiceA \trackBchannelA
  \context Voice = voiceB \trackBchannelB
>>


trackCchannelA = {
  
  \set Staff.instrumentName = "Alto"
  
}

trackCchannelB = \relative c {
  c'4*160/192 r4*32/192 d4*160/192 r4*32/192 c4*160/192 r4*32/192 
  | % 2
  f4*256/192 r4*32/192 e4*94/192 r4*2/192 d4*160/192 r4*32/192 
  | % 3
  c4*160/192 r4*32/192 bes4*160/192 r4*32/192 a4*160/192 r4*32/192 
  | % 4
  bes4*160/192 r4*32/192 bes4*160/192 r4*32/192 a4*160/192 r4*32/192 
  | % 5
  d4*160/192 r4*32/192 c4*160/192 r4*32/192 bes4*160/192 r4*32/192 
  | % 6
  a16*11 r16 
  | % 7
  c4*160/192 r4*32/192 d4*160/192 r4*32/192 c4*160/192 r4*32/192 
  | % 8
  f4*256/192 r4*32/192 e4*94/192 r4*2/192 d4*160/192 r4*32/192 
  | % 9
  c4*160/192 r4*32/192 bes4*160/192 r4*32/192 a4*160/192 r4*32/192 
  | % 10
  bes4*160/192 r4*32/192 bes4*160/192 r4*32/192 a4*160/192 r4*32/192 
  | % 11
  d4*160/192 r4*32/192 c4*160/192 r4*32/192 bes4*160/192 r4*32/192 
  | % 12
  a16*11 r16 
  | % 13
  f'4*160/192 r4*32/192 g4*160/192 r4*32/192 f4*160/192 r4*32/192 
  | % 14
  f16*11 r16 
  | % 15
  f4*160/192 r4*32/192 f4*160/192 r4*32/192 g4*160/192 r4*32/192 
  | % 16
  f4*160/192 r4*32/192 d4*94/192 r4*2/192 e4*94/192 r4*2/192 f4*160/192 
  r4*32/192 
  | % 17
  e16*11 r16 
  | % 18
  c4*160/192 r4*32/192 bes4*160/192 r4*32/192 bes4*160/192 r4*32/192 
  | % 19
  a4*160/192 r4*32/192 d4*160/192 r4*32/192 des4*160/192 r4*32/192 
  | % 20
  d16*7 r16 c4*94/192 r4*2/192 bes4*94/192 r4*2/192 
  | % 21
  a16*11 
}

trackC = <<

  \clef bass
  
  \context Voice = voiceA \trackCchannelA
  \context Voice = voiceB \trackCchannelB
>>


trackDchannelA = {
  
  \set Staff.instrumentName = "Tenor"
  
}

trackDchannelB = \relative c {
  a'4*160/192 r4*32/192 a4*160/192 r4*32/192 g4*160/192 r4*32/192 
  | % 2
  c4*256/192 r4*32/192 c4*94/192 r4*2/192 a4*160/192 r4*32/192 
  | % 3
  a4*160/192 r4*32/192 f4*160/192 r4*32/192 f4*160/192 r4*32/192 
  | % 4
  f4*160/192 r4*32/192 g4*160/192 r4*32/192 f4*160/192 r4*32/192 
  | % 5
  f4*160/192 r4*32/192 e16*7 r16 
  | % 6
  f16*11 r16 
  | % 7
  a4*160/192 r4*32/192 a4*160/192 r4*32/192 g4*160/192 r4*32/192 
  | % 8
  c4*256/192 r4*32/192 c4*94/192 r4*2/192 a4*160/192 r4*32/192 
  | % 9
  a4*160/192 r4*32/192 f4*160/192 r4*32/192 f4*160/192 r4*32/192 
  | % 10
  f4*160/192 r4*32/192 g4*160/192 r4*32/192 f4*160/192 r4*32/192 
  | % 11
  f4*160/192 r4*32/192 e16*7 r16 
  | % 12
  f16*11 r16 
  | % 13
  a4*160/192 r4*32/192 g4*160/192 r4*32/192 a4*160/192 r4*32/192 
  | % 14
  bes16*11 r16 
  | % 15
  c4*160/192 r4*32/192 bes4*160/192 r4*32/192 g4*160/192 r4*32/192 
  | % 16
  a4*160/192 r4*32/192 bes4*160/192 r4*32/192 c4*160/192 r4*32/192 
  | % 17
  c16*11 r16 
  | % 18
  f,4*160/192 r4*32/192 f4*160/192 r4*32/192 g4*160/192 r4*32/192 
  | % 19
  f4*160/192 r4*32/192 d4*160/192 r4*32/192 e4*160/192 r4*32/192 
  | % 20
  d4*160/192 r4*32/192 g4*94/192 r4*2/192 f4*94/192 r4*2/192 e4*160/192 
  r4*32/192 
  | % 21
  f16*11 
}

trackD = <<

  \clef bass
  
  \context Voice = voiceA \trackDchannelA
  \context Voice = voiceB \trackDchannelB
>>


trackEchannelA = {
  
  \set Staff.instrumentName = "Bass"
  
}

trackEchannelB = \relative c {
  f4*160/192 r4*32/192 d4*160/192 r4*32/192 e4*160/192 r4*32/192 
  | % 2
  f4*256/192 r4*32/192 c4*94/192 r4*2/192 d4*160/192 r4*32/192 
  | % 3
  a4*160/192 r4*32/192 bes4*160/192 r4*32/192 f4*160/192 r4*32/192 
  | % 4
  bes4*160/192 r4*32/192 g4*160/192 r4*32/192 d'4*160/192 r4*32/192 
  | % 5
  bes4*160/192 r4*32/192 c16*7 r16 
  | % 6
  f,16*11 r16 
  | % 7
  f'4*160/192 r4*32/192 d4*160/192 r4*32/192 e4*160/192 r4*32/192 
  | % 8
  f4*256/192 r4*32/192 c4*94/192 r4*2/192 d4*160/192 r4*32/192 
  | % 9
  a4*160/192 r4*32/192 bes4*160/192 r4*32/192 f4*160/192 r4*32/192 
  | % 10
  bes4*160/192 r4*32/192 g4*160/192 r4*32/192 d'4*160/192 r4*32/192 
  | % 11
  bes4*160/192 r4*32/192 c16*7 r16 
  | % 12
  f,16*11 r16 
  | % 13
  f'4*160/192 r4*32/192 e4*160/192 r4*32/192 f4*160/192 r4*32/192 
  | % 14
  bes,16*11 r16 
  | % 15
  f'4*160/192 r4*32/192 d4*160/192 r4*32/192 e4*160/192 r4*32/192 
  | % 16
  f4*160/192 r4*32/192 g4*160/192 r4*32/192 a4*94/192 r4*2/192 f4*94/192 
  r4*2/192 
  | % 17
  c16*11 r16 
  | % 18
  a4*160/192 r4*32/192 bes4*160/192 r4*32/192 g4*160/192 r4*32/192 
  | % 19
  d'4*160/192 r4*32/192 a4*160/192 r4*32/192 a4*160/192 r4*32/192 
  | % 20
  bes16*7 r16 c4*160/192 r4*32/192 
  | % 21
  f,16*11 
}

trackE = <<

  \clef bass
  
  \context Voice = voiceA \trackEchannelA
  \context Voice = voiceB \trackEchannelB
>>


trackF = <<
>>


trackGchannelA = {
  
  \set Staff.instrumentName = "Digital Hymn #1"
  
}

trackG = <<
  \context Voice = voiceA \trackGchannelA
>>


trackHchannelA = {
  
  \set Staff.instrumentName = "Praise to the Lord"
  
}

trackH = <<
  \context Voice = voiceA \trackHchannelA
>>


\score {
  <<
    \context Staff=trackB \trackA
    \context Staff=trackB \trackB
    \context Staff=trackC \trackA
    \context Staff=trackC \trackC
    \context Staff=trackD \trackA
    \context Staff=trackD \trackD
    \context Staff=trackE \trackA
    \context Staff=trackE \trackE
  >>
  \layout {}
  \midi {}
}
