% Lily was here -- automatically converted by c:/Program Files (x86)/LilyPond/usr/bin/midi2ly.py from output/midi/093-all-things-bright-and-beautiful.mid
\version "2.14.0"

\layout {
  \context {
    \Voice
    \remove "Note_heads_engraver"
    \consists "Completion_heads_engraver"
    \remove "Rest_engraver"
    \consists "Completion_rest_engraver"
  }
}

trackAchannelA = {


  \key g \major
    
  \time 4/4 
  

  \key g \major
  
  \tempo 4 = 100 
  
  % [MARKER] hasd037
  
  % [MARKER] By 17th Century English melody arr. by Martin Shaw
  
  % [MARKER] Public domain
  
  % [MARKER] Generated by NoteWorthy Composer
  \skip 4 
  \tempo 4 = 100 
  \skip 2*13 
  \tempo 4 = 89 
  \skip 4*28/192 
  \tempo 4 = 89 
  \skip 4*29/192 
  \tempo 4 = 88 
  \skip 4*29/192 
  \tempo 4 = 87 
  \skip 4*29/192 
  \tempo 4 = 86 
  \skip 4*28/192 
  \tempo 4 = 85 
  \skip 4*29/192 
  \tempo 4 = 83 
  \skip 4*29/192 
  \tempo 4 = 82 
  \skip 4*29/192 
  \tempo 4 = 82 
  \skip 4*29/192 
  \tempo 4 = 80 
  \skip 4*28/192 
  \tempo 4 = 80 
  \skip 4*29/192 
  \tempo 4 = 78 
  \skip 4*29/192 
  \tempo 4 = 77 
  \skip 4*29/192 
  \tempo 4 = 76 
  \skip 4*29/192 
  \tempo 4 = 75 
  \skip 4*28/192 
  \tempo 4 = 75 
  \skip 4*29/192 
  \tempo 4 = 73 
  \skip 4*29/192 
  \tempo 4 = 72 
  \skip 4*29/192 
  \tempo 4 = 72 
  \skip 4*29/192 
  \tempo 4 = 71 
  \skip 4*29/192 
  \tempo 4 = 69 
  \skip 4*2/192 
  \tempo 4 = 69 
  \skip 4*7/192 
  \tempo 4 = 69 
  \skip 4*9/192 
  \tempo 4 = 67 
  \skip 4*10/192 
  \tempo 4 = 67 
  \skip 4*13/192 
  \tempo 4 = 65 
  \skip 128 
  \tempo 4 = 64 
  \skip 4*10/192 
  \tempo 4 = 62 
  \skip 4*3/192 
  \tempo 4 = 61 
  \skip 128 
  \tempo 4 = 60 
  \skip 4*10/192 
  \tempo 4 = 60 
  \skip 128 
  \tempo 4 = 58 
  \skip 4*13/192 
  \tempo 4 = 57 
  \skip 4*10/192 
  \tempo 4 = 56 
  \skip 128 
  \tempo 4 = 55 
  \skip 4*7/192 
  \tempo 4 = 54 
  \skip 4*3/192 
  \tempo 4 = 53 
  \skip 128 
  \tempo 4 = 53 
  \skip 4*7/192 
  \tempo 4 = 52 
  \skip 64 
  \tempo 4 = 51 
  \skip 4*7/192 
  \tempo 4 = 50 
  \skip 4*3/192 
  \tempo 4 = 50 
  \skip 4*10/192 
  \tempo 4 = 50 
  \skip 4*3/192 
  \tempo 4 = 73 
  \skip 4*13/192 
  \tempo 4 = 80 
  \skip 128 
  \tempo 4 = 81 
  \skip 4*3/192 
  \tempo 4 = 86 
  \skip 4*3/192 
  \tempo 4 = 89 
  \skip 4*7/192 
  \tempo 4 = 90 
  \skip 4*3/192 
  \tempo 4 = 91 
  \skip 128 
  \tempo 4 = 93 
  \skip 4*4/192 
  \tempo 4 = 99 
  \skip 4*3/192 
  \tempo 4 = 100 
  \skip 4*16/192 
  \tempo 4 = 100 
  \skip 4*22/192 
  \tempo 4 = 100 
  \skip 4*58/192 
  \tempo 4 = 99 
  \skip 4*38/192 
  \tempo 4 = 100 
  \skip 4*5065/192 
  \tempo 4 = 100 
  \skip 128 
  \tempo 4 = 99 
  \skip 4*13/192 
  \tempo 4 = 98 
  \skip 4*38/192 
  \tempo 4 = 97 
  \skip 4*32/192 
  \tempo 4 = 97 
  \skip 4*13/192 
  \tempo 4 = 96 
  \skip 4*19/192 
  \tempo 4 = 96 
  \skip 4*3/192 
  \tempo 4 = 95 
  \skip 4*7/192 
  \tempo 4 = 94 
  \skip 128 
  \tempo 4 = 94 
  \skip 4*7/192 
  \tempo 4 = 93 
  \skip 128 
  \tempo 4 = 93 
  \skip 4*13/192 
  \tempo 4 = 93 
  \skip 4*13/192 
  \tempo 4 = 92 
  \skip 64 
  \tempo 4 = 91 
  \skip 4*16/192 
  \tempo 4 = 91 
  \skip 4*16/192 
  \tempo 4 = 90 
  \skip 4*10/192 
  \tempo 4 = 90 
  \skip 128 
  \tempo 4 = 89 
  \skip 4*10/192 
  \tempo 4 = 89 
  \skip 4*32/192 
  \tempo 4 = 88 
  \skip 4*10/192 
  \tempo 4 = 87 
  \skip 4*9/192 
  \tempo 4 = 86 
  \skip 4*10/192 
  \tempo 4 = 85 
  \skip 4*19/192 
  \tempo 4 = 85 
  \skip 4*10/192 
  \tempo 4 = 83 
  \skip 4*9/192 
  \tempo 4 = 83 
  \skip 4*13/192 
  \tempo 4 = 82 
  \skip 4*32/192 
  \tempo 4 = 82 
  \skip 4*10/192 
  \tempo 4 = 82 
  \skip 128 
  \tempo 4 = 81 
  \skip 128 
  \tempo 4 = 80 
  \skip 4*87/192 
  \tempo 4 = 80 
  \skip 4*45/192 
  \tempo 4 = 80 
  \skip 4*320/192 
  \tempo 4 = 80 
  \skip 128 
  \tempo 4 = 80 
  \skip 4*10/192 
  \tempo 4 = 82 
  \skip 64 
  \tempo 4 = 84 
  \skip 4*7/192 
  \tempo 4 = 86 
  \skip 4*3/192 
  \tempo 4 = 87 
  \skip 4*3/192 
  \tempo 4 = 88 
  \skip 4*3/192 
  \tempo 4 = 89 
  \skip 4*4/192 
  \tempo 4 = 90 
  \skip 128 
  \tempo 4 = 91 
  \skip 4*3/192 
  \tempo 4 = 92 
  \skip 4*7/192 
  \tempo 4 = 93 
  \skip 4*3/192 
  \tempo 4 = 94 
  \skip 128 
  \tempo 4 = 95 
  \skip 4*3/192 
  \tempo 4 = 96 
  \skip 4*13/192 
  \tempo 4 = 96 
  \skip 4*7/192 
  \tempo 4 = 97 
  \skip 64 
  \tempo 4 = 97 
  \skip 4*7/192 
  \tempo 4 = 98 
  \skip 4*3/192 
  \tempo 4 = 99 
  \skip 4*10/192 
  \tempo 4 = 100 
  \skip 4*3/192 
  \tempo 4 = 100 
  \skip 4*70/192 
  \tempo 4 = 99 
  \skip 4*23/192 
  \tempo 4 = 98 
  \skip 4*32/192 
  \tempo 4 = 99 
  \skip 4*44/192 
  \tempo 4 = 98 
  \skip 4*10/192 
  \tempo 4 = 99 
  \skip 4*26/192 
  \tempo 4 = 100 
  \skip 4*9/192 
  \tempo 4 = 98 
  \skip 4*95/192 
  \tempo 4 = 100 
  \skip 2*13 
  \tempo 4 = 89 
  \skip 4*28/192 
  \tempo 4 = 89 
  \skip 4*29/192 
  \tempo 4 = 88 
  \skip 4*29/192 
  \tempo 4 = 87 
  \skip 4*29/192 
  \tempo 4 = 86 
  \skip 4*28/192 
  \tempo 4 = 85 
  \skip 4*29/192 
  \tempo 4 = 83 
  \skip 4*29/192 
  \tempo 4 = 82 
  \skip 4*29/192 
  \tempo 4 = 82 
  \skip 4*29/192 
  \tempo 4 = 80 
  \skip 4*28/192 
  \tempo 4 = 80 
  \skip 4*29/192 
  \tempo 4 = 78 
  \skip 4*29/192 
  \tempo 4 = 77 
  \skip 4*29/192 
  \tempo 4 = 76 
  \skip 4*29/192 
  \tempo 4 = 75 
  \skip 4*28/192 
  \tempo 4 = 75 
  \skip 4*29/192 
  \tempo 4 = 73 
  \skip 4*29/192 
  \tempo 4 = 72 
  \skip 4*29/192 
  \tempo 4 = 72 
  \skip 4*29/192 
  \tempo 4 = 71 
  \skip 4*29/192 
  \tempo 4 = 69 
  \skip 4 
  \tempo 4 = 30 
  
}

trackA = <<
  \context Voice = voiceA \trackAchannelA
>>


trackBchannelA = {
  
  \set Staff.instrumentName = "Soprano"
  
}

trackBchannelB = \relative c {
  d''4*160/192 r4*32/192 b4*160/192 r4*32/192 c4*160/192 r4*32/192 b4*160/192 
  r4*32/192 
  | % 2
  a4*94/192 r4*2/192 g4*94/192 r4*2/192 fis4*94/192 r4*2/192 e4*94/192 
  r4*2/192 d4*160/192 r4*32/192 b'4*160/192 r4*32/192 
  | % 3
  c4*160/192 r4*32/192 e,4*160/192 r4*32/192 fis4*160/192 r4*32/192 e4*94/192 
  r4*2/192 fis4*94/192 r4*2/192 
  | % 4
  g16*15 r16 
  | % 5
  d'4*160/192 r4*32/192 b4*160/192 r4*32/192 c4*160/192 r4*32/192 b4*160/192 
  r4*32/192 
  | % 6
  a4*94/192 r4*2/192 g4*94/192 r4*2/192 fis4*94/192 r4*2/192 e4*94/192 
  r4*2/192 d4*160/192 r4*32/192 b'4*160/192 r4*32/192 
  | % 7
  c4*160/192 r4*32/192 e,4*160/192 r4*32/192 fis4*160/192 r4*32/192 e4*94/192 
  r4*2/192 fis4*94/192 r4*2/192 
  | % 8
  g16*11 r16 d4*160/192 r4*32/192 
  | % 9
  b4*160/192 r4*32/192 d4*160/192 r4*32/192 d4*160/192 r4*32/192 c4*94/192 
  r4*2/192 b4*94/192 r4*2/192 
  | % 10
  c4*160/192 r4*32/192 e16*7 r16 e4*160/192 r4*32/192 
  | % 11
  fis4*94/192 r4*2/192 g4*94/192 r4*2/192 a4*160/192 r4*32/192 fis4*94/192 
  r4*2/192 g4*94/192 r4*2/192 a4*160/192 r4*32/192 
  | % 12
  d,16*11 r16 g4*94/192 r4*2/192 a4*94/192 r4*2/192 
  | % 13
  b4*160/192 r4*32/192 a4*160/192 r4*32/192 g4*160/192 r4*32/192 a4*94/192 
  r4*2/192 b4*94/192 r4*2/192 
  | % 14
  c4. b4*94/192 r4*2/192 a4*160/192 r4*32/192 b4*94/192 r4*2/192 c4*94/192 
  r4*2/192 
  | % 15
  d4*160/192 r4*32/192 e,4*160/192 r4*32/192 fis4*160/192 r4*32/192 e4*94/192 
  r4*2/192 fis4*94/192 r4*2/192 
  | % 16
  g16*15 r16 
  | % 17
  d'4*160/192 r4*32/192 b4*160/192 r4*32/192 c4*160/192 r4*32/192 b4*160/192 
  r4*32/192 
  | % 18
  a4*94/192 r4*2/192 g4*94/192 r4*2/192 fis4*94/192 r4*2/192 e4*94/192 
  r4*2/192 d4*160/192 r4*32/192 b'4*160/192 r4*32/192 
  | % 19
  c4*160/192 r4*32/192 e,4*160/192 r4*32/192 fis4*160/192 r4*32/192 e4*94/192 
  r4*2/192 fis4*94/192 r4*2/192 
  | % 20
  g16*15 r16 
  | % 21
  d'4*160/192 r4*32/192 b4*160/192 r4*32/192 c4*160/192 r4*32/192 b4*160/192 
  r4*32/192 
  | % 22
  a4*94/192 r4*2/192 g4*94/192 r4*2/192 fis4*94/192 r4*2/192 e4*94/192 
  r4*2/192 d4*160/192 r4*32/192 b'4*160/192 r4*32/192 
  | % 23
  c4*160/192 r4*32/192 e,4*160/192 r4*32/192 fis4*160/192 r4*32/192 e4*94/192 
  r4*2/192 fis4*94/192 r4*2/192 
  | % 24
  g16*11 
}

trackB = <<
  \context Voice = voiceA \trackBchannelA
  \context Voice = voiceB \trackBchannelB
>>


trackCchannelA = {
  
  \set Staff.instrumentName = "Alto"
  
}

trackCchannelB = \relative c {
  d'4*160/192 r4*32/192 d4*160/192 r4*32/192 c4*160/192 r4*32/192 d4*160/192 
  r4*32/192 
  | % 2
  e4*160/192 r4*32/192 c4*160/192 r4*32/192 b4*160/192 r4*32/192 d4*160/192 
  r4*32/192 
  | % 3
  c4*160/192 r4*32/192 c4*160/192 r4*32/192 d4*160/192 r4*32/192 c4*160/192 
  r4*32/192 
  | % 4
  b4 c d fis8 e4*94/192 r4*2/192 
  | % 5
  d4*160/192 r4*32/192 d4*160/192 r4*32/192 c4*160/192 r4*32/192 d4*160/192 
  r4*32/192 
  | % 6
  e4*160/192 r4*32/192 c4*160/192 r4*32/192 b4*160/192 r4*32/192 d4*160/192 
  r4*32/192 
  | % 7
  c4*160/192 r4*32/192 c4*160/192 r4*32/192 d4*160/192 r4*32/192 c4*160/192 
  r4*32/192 
  | % 8
  b4 d8 c b4*160/192 r4*32/192 b4*160/192 r4*32/192 
  | % 9
  b4*160/192 r4*32/192 b4*160/192 r4*32/192 b4*160/192 r4*32/192 g4*160/192 
  r4*32/192 
  | % 10
  g4*160/192 r4*32/192 c16*7 r16 c4*160/192 r4*32/192 
  | % 11
  c4*160/192 r4*32/192 c4*160/192 r4*32/192 d4*160/192 r4*32/192 d4*160/192 
  r4*32/192 
  | % 12
  d4 c b4*160/192 r4*32/192 c4*94/192 r4*2/192 c4*94/192 r4*2/192 
  | % 13
  d4*160/192 r4*32/192 dis4*160/192 r4*32/192 e4*160/192 r4*32/192 e4*94/192 
  r4*2/192 d4*94/192 r4*2/192 
  | % 14
  c4 e4*160/192 r4*32/192 fis4*94/192 r4*2/192 e4*94/192 r4*2/192 d4*160/192 
  r4*32/192 
  | % 15
  d4*160/192 r4*32/192 c4*94/192 r4*2/192 b4*94/192 r4*2/192 a4*160/192 
  r4*32/192 c4*160/192 r4*32/192 
  | % 16
  b16*15 r16 
  | % 17
  d4*160/192 r4*32/192 d4*160/192 r4*32/192 c4*160/192 r4*32/192 d4*160/192 
  r4*32/192 
  | % 18
  e4*160/192 r4*32/192 c4*160/192 r4*32/192 b4*160/192 r4*32/192 d4*160/192 
  r4*32/192 
  | % 19
  c4*160/192 r4*32/192 c4*160/192 r4*32/192 d4*160/192 r4*32/192 c4*160/192 
  r4*32/192 
  | % 20
  b4 c d fis8 e4*94/192 r4*2/192 
  | % 21
  d4*160/192 r4*32/192 d4*160/192 r4*32/192 c4*160/192 r4*32/192 d4*160/192 
  r4*32/192 
  | % 22
  e4*160/192 r4*32/192 c4*160/192 r4*32/192 b4*160/192 r4*32/192 d4*160/192 
  r4*32/192 
  | % 23
  c4*160/192 r4*32/192 c4*160/192 r4*32/192 d4*160/192 r4*32/192 c4*160/192 
  r4*32/192 
  | % 24
  b4 d8 c b4*160/192 
}

trackC = <<

  \clef bass
  
  \context Voice = voiceA \trackCchannelA
  \context Voice = voiceB \trackCchannelB
>>


trackDchannelA = {
  
  \set Staff.instrumentName = "Tenor"
  
}

trackDchannelB = \relative c {
  b' r4*32/192 g4*160/192 r4*32/192 g4*160/192 r4*32/192 fis4*160/192 
  r4*32/192 
  | % 2
  g4*160/192 r4*32/192 g4*160/192 r4*32/192 g4*160/192 r4*32/192 g4*160/192 
  r4*32/192 
  | % 3
  e4*160/192 r4*32/192 a4*160/192 r4*32/192 a4*160/192 r4*32/192 a4*160/192 
  r4*32/192 
  | % 4
  g4 a b c4*160/192 r4*32/192 
  | % 5
  b4*160/192 r4*32/192 g4*160/192 r4*32/192 g4*160/192 r4*32/192 fis4*160/192 
  r4*32/192 
  | % 6
  g4*160/192 r4*32/192 g4*160/192 r4*32/192 g4*160/192 r4*32/192 gis4*160/192 
  r4*32/192 
  | % 7
  a4*160/192 r4*32/192 a4*160/192 r4*32/192 a4*160/192 r4*32/192 d,4*160/192 
  r4*32/192 
  | % 8
  d4 e d4*160/192 r4*32/192 d4*160/192 r4*32/192 
  | % 9
  g4*160/192 r4*32/192 g4*160/192 r4*32/192 g4*160/192 r4*32/192 g4*160/192 
  r4*32/192 
  | % 10
  g4*160/192 r4*32/192 g16*7 r16 a4*160/192 r4*32/192 
  | % 11
  a4*94/192 r4*2/192 g4*94/192 r4*2/192 fis4*160/192 r4*32/192 a4*94/192 
  r4*2/192 g4*94/192 r4*2/192 fis4*160/192 r4*32/192 
  | % 12
  g4 e8 fis g4*160/192 r4*32/192 g4*94/192 r4*2/192 fis4*94/192 
  r4*2/192 
  | % 13
  g4*160/192 r4*32/192 a4*160/192 r4*32/192 b4*160/192 r4*32/192 a4*94/192 
  r4*2/192 gis4*94/192 r4*2/192 
  | % 14
  a4 g4*160/192 r4*32/192 fis4*160/192 r4*32/192 fis4*94/192 
  r4*2/192 e4*94/192 r4*2/192 
  | % 15
  d4*160/192 r4*32/192 g4*160/192 r4*32/192 d4*160/192 r4*32/192 d4*160/192 
  r4*32/192 
  | % 16
  d16*15 r16 
  | % 17
  b'4*160/192 r4*32/192 g4*160/192 r4*32/192 g4*160/192 r4*32/192 fis4*160/192 
  r4*32/192 
  | % 18
  g4*160/192 r4*32/192 g4*160/192 r4*32/192 g4*160/192 r4*32/192 g4*160/192 
  r4*32/192 
  | % 19
  e4*160/192 r4*32/192 a4*160/192 r4*32/192 a4*160/192 r4*32/192 a4*160/192 
  r4*32/192 
  | % 20
  g4 a b c4*160/192 r4*32/192 
  | % 21
  b4*160/192 r4*32/192 g4*160/192 r4*32/192 g4*160/192 r4*32/192 fis4*160/192 
  r4*32/192 
  | % 22
  g4*160/192 r4*32/192 g4*160/192 r4*32/192 g4*160/192 r4*32/192 gis4*160/192 
  r4*32/192 
  | % 23
  a4*160/192 r4*32/192 a4*160/192 r4*32/192 a4*160/192 r4*32/192 d,4*160/192 
  r4*32/192 
  | % 24
  d4 e d4*160/192 
}

trackD = <<

  \clef bass
  
  \context Voice = voiceA \trackDchannelA
  \context Voice = voiceB \trackDchannelB
>>


trackEchannelA = {
  
  \set Staff.instrumentName = "Bass"
  
}

trackEchannelB = \relative c {
  g' r4*32/192 fis4*160/192 r4*32/192 e4*160/192 r4*32/192 d4*160/192 
  r4*32/192 
  | % 2
  c4*160/192 r4*32/192 e4*160/192 r4*32/192 g4*160/192 r4*32/192 g,4*160/192 
  r4*32/192 
  | % 3
  a4*160/192 r4*32/192 a4*160/192 r4*32/192 d4*160/192 r4*32/192 d4*160/192 
  r4*32/192 
  | % 4
  g16*15 r16 
  | % 5
  g4*160/192 r4*32/192 g4*94/192 r4*2/192 f4*94/192 r4*2/192 e4*160/192 
  r4*32/192 d4*160/192 r4*32/192 
  | % 6
  c4*160/192 r4*32/192 e4*160/192 r4*32/192 g4*160/192 r4*32/192 e4*160/192 
  r4*32/192 
  | % 7
  a,4*160/192 r4*32/192 a4*160/192 r4*32/192 d4*160/192 r4*32/192 d4*160/192 
  r4*32/192 
  | % 8
  g,16*11 r16 g4*160/192 r4*32/192 
  | % 9
  g'4*160/192 r4*32/192 fis4*160/192 r4*32/192 f4*160/192 r4*32/192 e4*94/192 
  r4*2/192 d4*94/192 r4*2/192 
  | % 10
  e4*160/192 r4*32/192 c4 b4*160/192 r4*32/192 a4*160/192 r4*32/192 
  | % 11
  d4*160/192 r4*32/192 d4*160/192 r4*32/192 c4*160/192 r4*32/192 c4*160/192 
  r4*32/192 
  | % 12
  b4 a g4*160/192 r4*32/192 e'4*94/192 r4*2/192 d4*94/192 r4*2/192 
  | % 13
  g4*160/192 r4*32/192 fis4*160/192 r4*32/192 e4*160/192 r4*32/192 c4*94/192 
  r4*2/192 b4*94/192 r4*2/192 
  | % 14
  a16*7 r16 d4*160/192 r4*32/192 c4*160/192 r4*32/192 
  | % 15
  b4*160/192 r4*32/192 c4*160/192 r4*32/192 d4*160/192 r4*32/192 d4*160/192 
  r4*32/192 
  | % 16
  g,16*15 r16 
  | % 17
  g'4*160/192 r4*32/192 fis4*160/192 r4*32/192 e4*160/192 r4*32/192 d4*160/192 
  r4*32/192 
  | % 18
  c4*160/192 r4*32/192 e4*160/192 r4*32/192 g4*160/192 r4*32/192 g,4*160/192 
  r4*32/192 
  | % 19
  a4*160/192 r4*32/192 a4*160/192 r4*32/192 d4*160/192 r4*32/192 d4*160/192 
  r4*32/192 
  | % 20
  g16*15 r16 
  | % 21
  g4*160/192 r4*32/192 g4*94/192 r4*2/192 f4*94/192 r4*2/192 e4*160/192 
  r4*32/192 d4*160/192 r4*32/192 
  | % 22
  c4*160/192 r4*32/192 e4*160/192 r4*32/192 g4*160/192 r4*32/192 e4*160/192 
  r4*32/192 
  | % 23
  a,4*160/192 r4*32/192 a4*160/192 r4*32/192 d4*160/192 r4*32/192 d4*160/192 
  r4*32/192 
  | % 24
  g,16*11 
}

trackE = <<

  \clef bass
  
  \context Voice = voiceA \trackEchannelA
  \context Voice = voiceB \trackEchannelB
>>


trackF = <<
>>


trackGchannelA = {
  
  \set Staff.instrumentName = "Digital Hymn#93"
  
}

trackG = <<
  \context Voice = voiceA \trackGchannelA
>>


trackHchannelA = {
  
  \set Staff.instrumentName = "All Things Bright and Beautiful"
  
}

trackH = <<
  \context Voice = voiceA \trackHchannelA
>>


\score {
  <<
    \context Staff=trackB \trackA
    \context Staff=trackB \trackB
    \context Staff=trackC \trackA
    \context Staff=trackC \trackC
    \context Staff=trackD \trackA
    \context Staff=trackD \trackD
    \context Staff=trackE \trackA
    \context Staff=trackE \trackE
  >>
  \layout {}
  \midi {}
}
