% Lily was here -- automatically converted by c:/Program Files (x86)/LilyPond/usr/bin/midi2ly.py from output/midi/109-marvelous-grace.mid
\version "2.14.0"

\layout {
  \context {
    \Voice
    \remove "Note_heads_engraver"
    \consists "Completion_heads_engraver"
    \remove "Rest_engraver"
    \consists "Completion_rest_engraver"
  }
}

trackAchannelA = {


  \key g \major
    
  \time 6/8 
  

  \key g \major
  
  \tempo 4 = 67 
  
  % [MARKER] Quartet Template
  
  % [MARKER] By <Name>
  
  % [MARKER] Copyright ~ <Year> by <Name>
  
  % [MARKER] All Rights Reserved
  
  % [MARKER] Generated by NoteWorthy Composer
  \skip 4*21 
  \tempo 4 = 67 
  \skip 4*128/192 
  \tempo 4 = 67 
  \skip 4*128/192 
  \tempo 4 = 65 
  \skip 4*128/192 
  \tempo 4 = 64 
  \skip 4*128/192 
  \tempo 4 = 64 
  \skip 4*128/192 
  \tempo 4 = 62 
  \skip 4*128/192 
  \tempo 4 = 61 
  \skip 2 
  | % 10
  
  \tempo 4 = 65 
  \skip 2 
  \tempo 4 = 67 
  \skip 2 
  \tempo 4 = 67 
  \skip 2*7 
  \tempo 4 = 65 
  \skip 4*32/192 
  \tempo 4 = 64 
  \skip 4*32/192 
  \tempo 4 = 64 
  \skip 4*32/192 
  \tempo 4 = 62 
  \skip 4*32/192 
  \tempo 4 = 61 
  \skip 4*32/192 
  \tempo 4 = 60 
  \skip 4*32/192 
  \tempo 4 = 60 
  \skip 4*32/192 
  \tempo 4 = 59 
  \skip 4*32/192 
  \tempo 4 = 57 
  \skip 4*32/192 
  \tempo 4 = 56 
  \skip 4*32/192 
  \tempo 4 = 55 
  \skip 4*32/192 
  \tempo 4 = 55 
  \skip 4*32/192 
  \tempo 4 = 54 
  \skip 8 
  \tempo 4 = 50 
  
}

trackA = <<
  \context Voice = voiceA \trackAchannelA
>>


trackBchannelA = {
  
  \set Staff.instrumentName = "Soprano"
  
}

trackBchannelB = \relative c {
  r4 g''4*142/192 r4*2/192 fis4*46/192 r4*2/192 g4*94/192 r4*2/192 a4*94/192 
  r4*2/192 
  | % 2
  g4*94/192 r4*2/192 a4*94/192 r4*2/192 b4*160/192 r4*32/192 a4*94/192 
  r4*2/192 g4*256/192 r4*32/192 fis4*94/192 r4*2/192 fis4*94/192 
  r4*2/192 g4*94/192 r4*2/192 a4*256/192 r4*32/192 g4*94/192 r4*2/192 g4*94/192 
  r4*2/192 a4*94/192 r4*2/192 b4*256/192 r4*32/192 g4*142/192 r4*2/192 fis4*46/192 
  r4*2/192 g4*94/192 r4*2/192 a4*94/192 r4*2/192 
  | % 6
  g4*94/192 r4*2/192 a4*94/192 r4*2/192 b4*160/192 r4*32/192 a4*94/192 
  r4*2/192 g4*256/192 r4*32/192 a4*142/192 r4*2/192 a4*46/192 r4*2/192 b4*94/192 
  r4*2/192 c4*94/192 r4*2/192 
  | % 8
  b4*94/192 r4*2/192 a4*94/192 r4*2/192 g4*160/192 r4*32/192 fis4*94/192 
  r4*2/192 g4*256/192 r4*32/192 b4*256/192 r4*32/192 g4*256/192 
  r4*32/192 c4*256/192 r4*32/192 b4*256/192 r4*32/192 a4*142/192 
  r4*2/192 a4*46/192 r4*2/192 a4*94/192 r4*2/192 a4*94/192 r4*2/192 
  | % 12
  b4*94/192 r4*2/192 a4*94/192 r4*2/192 g4*160/192 r4*32/192 c4*94/192 
  r4*2/192 b4*256/192 r4*32/192 b4*256/192 r4*32/192 g4*256/192 
  r4*32/192 c4*256/192 r4*32/192 b4*256/192 r4*32/192 a4*142/192 
  r4*2/192 a4*46/192 r4*2/192 b4*94/192 r4*2/192 c4*94/192 r4*2/192 
  | % 16
  b4*94/192 r4*2/192 a4*94/192 r4*2/192 g4*160/192 r4*32/192 fis4*94/192 
  r4*2/192 g4*256/192 
}

trackB = <<
  \context Voice = voiceA \trackBchannelA
  \context Voice = voiceB \trackBchannelB
>>


trackCchannelA = {
  
  \set Staff.instrumentName = "Alto"
  
}

trackCchannelB = \relative c {
  r4 d'4*142/192 r4*2/192 d4*46/192 r4*2/192 d4*94/192 r4*2/192 fis4*94/192 
  r4*2/192 
  | % 2
  e4*94/192 r4*2/192 d4*94/192 r4*2/192 d4*160/192 r4*32/192 d4*94/192 
  r4*2/192 d4*256/192 r4*32/192 d4*94/192 r4*2/192 d4*94/192 r4*2/192 d4*94/192 
  r4*2/192 fis4*256/192 r4*32/192 d4*94/192 r4*2/192 d4*94/192 
  r4*2/192 d4*94/192 r4*2/192 g4*256/192 r4*32/192 d4*142/192 r4*2/192 d4*46/192 
  r4*2/192 d4*94/192 r4*2/192 fis4*94/192 r4*2/192 
  | % 6
  e4*94/192 r4*2/192 d4*94/192 r4*2/192 d4*160/192 r4*32/192 fis4*94/192 
  r4*2/192 e4*256/192 r4*32/192 e4*142/192 r4*2/192 e4*46/192 r4*2/192 g4*94/192 
  r4*2/192 g4*94/192 r4*2/192 
  | % 8
  g4*94/192 r4*2/192 e4*94/192 r4*2/192 d4*160/192 r4*32/192 d4*94/192 
  r4*2/192 d4*256/192 r4*32/192 g4*142/192 r4*2/192 g4*46/192 r4*2/192 g4*94/192 
  r4*2/192 d4*256/192 r4*32/192 g4*142/192 r4*2/192 g4*46/192 r4*2/192 g4*94/192 
  r4*2/192 g4*256/192 r4*32/192 fis4*142/192 r4*2/192 fis4*46/192 
  r4*2/192 fis4*94/192 r4*2/192 fis4*94/192 r4*2/192 
  | % 12
  fis4*94/192 r4*2/192 d4*94/192 r4*2/192 d4*160/192 r4*32/192 g4*94/192 
  r4*2/192 g4*256/192 r4*32/192 g4*142/192 r4*2/192 g4*46/192 r4*2/192 g4*94/192 
  r4*2/192 d4*256/192 r4*32/192 g4*142/192 r4*2/192 g4*46/192 r4*2/192 g4*94/192 
  r4*2/192 g4*256/192 r4*32/192 e4*142/192 r4*2/192 e4*46/192 r4*2/192 g4*94/192 
  r4*2/192 g4*94/192 r4*2/192 
  | % 16
  g4*94/192 r4*2/192 e4*94/192 r4*2/192 d4*160/192 r4*32/192 d4*94/192 
  r4*2/192 d4*256/192 
}

trackC = <<
  \context Voice = voiceA \trackCchannelA
  \context Voice = voiceB \trackCchannelB
>>


trackDchannelA = {
  
  \set Staff.instrumentName = "Tenor"
  
}

trackDchannelB = \relative c {
  r4 b'4*142/192 r4*2/192 a4*46/192 r4*2/192 b4*94/192 r4*2/192 c4*94/192 
  r4*2/192 
  | % 2
  b4*94/192 r4*2/192 a4*94/192 r4*2/192 g4*160/192 r4*32/192 c4*94/192 
  r4*2/192 b4*256/192 r4*32/192 a4*94/192 r4*2/192 a4*94/192 r4*2/192 b4*94/192 
  r4*2/192 c4*256/192 r4*32/192 b4*94/192 r4*2/192 b4*94/192 r4*2/192 c4*94/192 
  r4*2/192 d4*256/192 r4*32/192 b4*142/192 r4*2/192 a4*46/192 r4*2/192 b4*94/192 
  r4*2/192 c4*94/192 r4*2/192 
  | % 6
  b4*94/192 r4*2/192 a4*94/192 r4*2/192 g4*160/192 r4*32/192 c4*94/192 
  r4*2/192 b4*256/192 r4*32/192 c4*142/192 r4*2/192 c4*46/192 r4*2/192 d4*94/192 
  r4*2/192 e4*94/192 r4*2/192 
  | % 8
  d4*94/192 r4*2/192 c4*94/192 r4*2/192 b4*160/192 r4*32/192 a4*94/192 
  r4*2/192 b4*256/192 r4*32/192 d4*142/192 r4*2/192 d4*46/192 r4*2/192 d4*94/192 
  r4*2/192 b4*256/192 r4*32/192 e4*142/192 r4*2/192 e4*46/192 r4*2/192 e4*94/192 
  r4*2/192 d4*256/192 r4*32/192 c4*142/192 r4*2/192 c4*46/192 r4*2/192 c4*94/192 
  r4*2/192 c4*94/192 r4*2/192 
  | % 12
  d4*94/192 r4*2/192 c4*94/192 r4*2/192 b4*160/192 r4*32/192 e4*94/192 
  r4*2/192 d4*256/192 r4*32/192 d4*142/192 r4*2/192 d4*46/192 r4*2/192 d4*94/192 
  r4*2/192 b4*256/192 r4*32/192 e4*142/192 r4*2/192 e4*46/192 r4*2/192 e4*94/192 
  r4*2/192 d4*256/192 r4*32/192 c4*142/192 r4*2/192 c4*46/192 r4*2/192 d4*94/192 
  r4*2/192 e4*94/192 r4*2/192 
  | % 16
  d4*94/192 r4*2/192 c4*94/192 r4*2/192 b4*160/192 r4*32/192 a4*94/192 
  r4*2/192 b4*256/192 
}

trackD = <<

  \clef bass
  
  \context Voice = voiceA \trackDchannelA
  \context Voice = voiceB \trackDchannelB
>>


trackEchannelA = {
  
  \set Staff.instrumentName = "Bass"
  
}

trackEchannelB = \relative c {
  r4 g'4*142/192 r4*2/192 g4*46/192 r4*2/192 g4*94/192 r4*2/192 d4*94/192 
  r4*2/192 
  | % 2
  e4*94/192 r4*2/192 fis4*94/192 r4*2/192 g4*160/192 r4*32/192 d4*94/192 
  r4*2/192 g4*256/192 r4*32/192 d4*94/192 r4*2/192 d4*94/192 r4*2/192 d4*94/192 
  r4*2/192 d4*256/192 r4*32/192 g4*94/192 r4*2/192 g4*94/192 r4*2/192 g4*94/192 
  r4*2/192 g4*256/192 r4*32/192 g4*142/192 r4*2/192 g4*46/192 r4*2/192 g4*94/192 
  r4*2/192 d4*94/192 r4*2/192 
  | % 6
  e4*94/192 r4*2/192 fis4*94/192 r4*2/192 g4*160/192 r4*32/192 d4*94/192 
  r4*2/192 e4*256/192 r4*32/192 c4*142/192 r4*2/192 c4*46/192 r4*2/192 b4*94/192 
  r4*2/192 a4*94/192 r4*2/192 
  | % 8
  b4*94/192 r4*2/192 c4*94/192 r4*2/192 d4*160/192 r4*32/192 d4*94/192 
  r4*2/192 g4*256/192 r4*32/192 g4*256/192 r4*32/192 g4*256/192 
  r4*32/192 g4*256/192 r4*32/192 g4*256/192 r4*32/192 d4*142/192 
  r4*2/192 d4*46/192 r4*2/192 d4*94/192 r4*2/192 d4*94/192 r4*2/192 
  | % 12
  d4*94/192 r4*2/192 d4*94/192 r4*2/192 g4*160/192 r4*32/192 g4*94/192 
  r4*2/192 g4*256/192 r4*32/192 g4*256/192 r4*32/192 g4*256/192 
  r4*32/192 g4*256/192 r4*32/192 g4*256/192 r4*32/192 c,4*142/192 
  r4*2/192 c4*46/192 r4*2/192 b4*94/192 r4*2/192 a4*94/192 r4*2/192 
  | % 16
  b4*94/192 r4*2/192 c4*94/192 r4*2/192 d4*160/192 r4*32/192 d4*94/192 
  r4*2/192 <g g, >4*256/192 
}

trackE = <<

  \clef bass
  
  \context Voice = voiceA \trackEchannelA
  \context Voice = voiceB \trackEchannelB
>>


trackF = <<
>>


trackGchannelA = {
  
  \set Staff.instrumentName = "Digital Hymn #109"
  
}

trackG = <<
  \context Voice = voiceA \trackGchannelA
>>


trackHchannelA = {
  
  \set Staff.instrumentName = "Marvelous Grace"
  
}

trackH = <<
  \context Voice = voiceA \trackHchannelA
>>


\score {
  <<
    \context Staff=trackB \trackA
    \context Staff=trackB \trackB
    \context Staff=trackC \trackA
    \context Staff=trackC \trackC
    \context Staff=trackD \trackA
    \context Staff=trackD \trackD
    \context Staff=trackE \trackA
    \context Staff=trackE \trackE
  >>
  \layout {}
  \midi {}
}
