% Lily was here -- automatically converted by c:/Program Files (x86)/LilyPond/usr/bin/midi2ly.py from output/midi/421-for-all-the-saints.mid
\version "2.14.0"

\layout {
  \context {
    \Voice
    \remove "Note_heads_engraver"
    \consists "Completion_heads_engraver"
    \remove "Rest_engraver"
    \consists "Completion_rest_engraver"
  }
}

trackAchannelA = {


  \key g \major
    
  \time 4/4 
  

  \key g \major
  
  \tempo 4 = 100 
  
  % [MARKER] Vocal with Piano Accompaniment Template
  
  % [MARKER] By <Name>
  
  % [MARKER] Copyright ~ <Year> by <Name>
  
  % [MARKER] All Rights Reserved
  
  % [MARKER] Generated by NoteWorthy Composer
  
}

trackA = <<
  \context Voice = voiceA \trackAchannelA
>>


trackBchannelA = {
  
  \set Staff.instrumentName = "Organ"
  
}

trackBchannelB = \relative c {
  r4 d'' b a 
  | % 2
  g2. d4 
  | % 3
  e g a d, 
  | % 4
  b'2. b4 
  | % 5
  a2. g4 
  | % 6
  fis2 fis 
  | % 7
  g4 a fis e 
  | % 8
  d2. d4 
  | % 9
  g2 g 
  | % 10
  d'2. d4 
  | % 11
  c d c8 b a g 
  | % 12
  a2 d 
  | % 13
  e4 d8 c d2 
  | % 14
  g,2. a8 b 
  | % 15
  c4 b a2 
  | % 16
  g1 
  | % 17
  r4 d' b a 
  | % 18
  g2. d4 
  | % 19
  e g a d, 
  | % 20
  b'2. b4 
  | % 21
  a2. g4 
  | % 22
  fis2 fis 
  | % 23
  g4 a fis e 
  | % 24
  d2. d4 
  | % 25
  g2 g 
  | % 26
  d'2. d4 
  | % 27
  c d c8 b a g 
  | % 28
  a2 d 
  | % 29
  e4 d8 c d2 
  | % 30
  g,2. a8 b 
  | % 31
  c4 b a2 
  | % 32
  g1 
  | % 33
  r4 d' b a 
  | % 34
  g2. d4 
  | % 35
  e g a d, 
  | % 36
  b'2. b4 
  | % 37
  a2. g4 
  | % 38
  fis2 fis 
  | % 39
  g4 a fis e 
  | % 40
  d2. d4 
  | % 41
  g2 g 
  | % 42
  d'2. d4 
  | % 43
  c d c8 b a g 
  | % 44
  a2 d 
  | % 45
  e4 d8 c d2 
  | % 46
  g,2. a8 b 
  | % 47
  c4 b a2 
  | % 48
  g1 
  | % 49
  r4 d' b a 
  | % 50
  g2. d4 
  | % 51
  e g a d, 
  | % 52
  b'2. b4 
  | % 53
  a2. g4 
  | % 54
  fis2 fis 
  | % 55
  g4 a fis e 
  | % 56
  d2. d4 
  | % 57
  g2 g 
  | % 58
  d'2. d4 
  | % 59
  c d c8 b a g 
  | % 60
  a2 d 
  | % 61
  e4 d8 c d2 
  | % 62
  g,2. a8 b 
  | % 63
  c4 b a2 
  | % 64
  g1 
  | % 65
  r4 d' b a 
  | % 66
  g2. d4 
  | % 67
  e g a d, 
  | % 68
  b'2. b4 
  | % 69
  a2. g4 
  | % 70
  fis2 fis 
  | % 71
  g4 a fis e 
  | % 72
  d2. d4 
  | % 73
  g2 g 
  | % 74
  d'2. d4 
  | % 75
  c d c8 b a g 
  | % 76
  a2 d 
  | % 77
  e4 d8 c d2 
  | % 78
  g,2. a8 b 
  | % 79
  c4 b a2 
  | % 80
  g1 
  | % 81
  
}

trackB = <<
  \context Voice = voiceA \trackBchannelA
  \context Voice = voiceB \trackBchannelB
>>


trackCchannelA = {
  
  \set Staff.instrumentName = "Right Hand"
  
}

trackCchannelB = \relative c {
  \voiceTwo
  r4 <d'' d, g b > <b g e > <a fis c > 
  | % 2
  b,2 c4 <d g, > 
  | % 3
  <e g, > <g d > <a e c > d, 
  | % 4
  <b' g d >2. <b g d >4 
  | % 5
  <a d, >2. <g cis, a >4 
  | % 6
  <fis d a >2 <fis d a > 
  | % 7
  <g d g, >4 <a d, a > <fis d b > <e cis g > 
  | % 8
  <d a fis >2. <d a fis >4 
  | % 9
  <g g, >2 <g g, > 
  | % 10
  <d' d, g b >2. <d b g >4 
  | % 11
  <c g c, > <d a > c8 b a g 
  | % 12
  <a fis d >2 <g d >4 <b fis > 
  | % 13
  e d8 c d,4 e8 fis 
  | % 14
  g2. a8 b 
  | % 15
  <c g e >4 <b g d > <g d > <fis c > 
  | % 16
  <g d b >1 
  | % 17
  r4 <d' d, g b > <b g e > <a fis c > 
  | % 18
  b,2 c4 <d g, > 
  | % 19
  <e g, > <g d > <a e c > d, 
  | % 20
  <b' g d >2. <b g d >4 
  | % 21
  <a d, >2. <g cis, a >4 
  | % 22
  <fis d a >2 <fis d a > 
  | % 23
  <g d g, >4 <a d, a > <fis d b > <e cis g > 
  | % 24
  <d a fis >2. <d a fis >4 
  | % 25
  <g g, >2 <g g, > 
  | % 26
  <d' d, g b >2. <d b g >4 
  | % 27
  <c g c, > <d a > c8 b a g 
  | % 28
  <a fis d >2 <g d >4 <b fis > 
  | % 29
  e d8 c d,4 e8 fis 
  | % 30
  g2. a8 b 
  | % 31
  <c g e >4 <b g d > <g d > <fis c > 
  | % 32
  <g d b >1 
  | % 33
  r4 <d' d, g b > <b g e > <a fis c > 
  | % 34
  b,2 c4 <d g, > 
  | % 35
  <e g, > <g d > <a e c > d, 
  | % 36
  <b' g d >2. <b g d >4 
  | % 37
  <a d, >2. <g cis, a >4 
  | % 38
  <fis d a >2 <fis d a > 
  | % 39
  <g d g, >4 <a d, a > <fis d b > <e cis g > 
  | % 40
  <d a fis >2. <d a fis >4 
  | % 41
  <g g, >2 <g g, > 
  | % 42
  <d' d, g b >2. <d b g >4 
  | % 43
  <c g c, > <d a > c8 b a g 
  | % 44
  <a fis d >2 <g d >4 <b fis > 
  | % 45
  e d8 c d,4 e8 fis 
  | % 46
  g2. a8 b 
  | % 47
  <c g e >4 <b g d > <g d > <fis c > 
  | % 48
  <g d b >1 
  | % 49
  r4 <d' d, g b > <b g e > <a fis c > 
  | % 50
  b,2 c4 <d g, > 
  | % 51
  <e g, > <g d > <a e c > d, 
  | % 52
  <b' g d >2. <b g d >4 
  | % 53
  <a d, >2. <g cis, a >4 
  | % 54
  <fis d a >2 <fis d a > 
  | % 55
  <g d g, >4 <a d, a > <fis d b > <e cis g > 
  | % 56
  <d a fis >2. <d a fis >4 
  | % 57
  <g g, >2 <g g, > 
  | % 58
  <d' d, g b >2. <d b g >4 
  | % 59
  <c g c, > <d a > c8 b a g 
  | % 60
  <a fis d >2 <g d >4 <b fis > 
  | % 61
  e d8 c d,4 e8 fis 
  | % 62
  g2. a8 b 
  | % 63
  <c g e >4 <b g d > <g d > <fis c > 
  | % 64
  <g d b >1 
  | % 65
  r4 <d' d, g b > <b g e > <a fis c > 
  | % 66
  b,2 c4 <d g, > 
  | % 67
  <e g, > <g d > <a e c > d, 
  | % 68
  <b' g d >2. <b g d >4 
  | % 69
  <a d, >2. <g cis, a >4 
  | % 70
  <fis d a >2 <fis d a > 
  | % 71
  <g d g, >4 <a d, a > <fis d b > <e cis g > 
  | % 72
  <d a fis >2. <d a fis >4 
  | % 73
  <g g, >2 <g g, > 
  | % 74
  <d' d, g b >2. <d b g >4 
  | % 75
  <c g c, > <d a > c8 b a g 
  | % 76
  <a fis d >2 <g d >4 <b fis > 
  | % 77
  e d8 c d,4 e8 fis 
  | % 78
  g2. a8 b 
  | % 79
  <c g e >4 <b g d > <g d > <fis c > 
  | % 80
  <g d b >1 
  | % 81
  
}

trackCchannelBvoiceB = \relative c {
  \voiceOne
  r1 
  | % 2
  <g'' e >2. r4*35 <g d >4 d 
  | % 12
  r2 d' 
  | % 13
  <g, e > <d' g, > 
  | % 14
  r1. a2 
  | % 16
  r1*2 <g e >2. r4*35 <g d >4 d 
  | % 28
  r2 d' 
  | % 29
  <g, e > <d' g, > 
  | % 30
  r1. a2 
  | % 32
  r1*2 <g e >2. r4*35 <g d >4 d 
  | % 44
  r2 d' 
  | % 45
  <g, e > <d' g, > 
  | % 46
  r1. a2 
  | % 48
  r1*2 <g e >2. r4*35 <g d >4 d 
  | % 60
  r2 d' 
  | % 61
  <g, e > <d' g, > 
  | % 62
  r1. a2 
  | % 64
  r1*2 <g e >2. r4*35 <g d >4 d 
  | % 76
  r2 d' 
  | % 77
  <g, e > <d' g, > 
  | % 78
  r1. a2 
  | % 80
  
}

trackC = <<
  \context Voice = voiceA \trackCchannelA
  \context Voice = voiceB \trackCchannelB
  \context Voice = voiceC \trackCchannelBvoiceB
>>


trackDchannelA = {
  
  \set Staff.instrumentName = "Left Hand"
  
}

trackDchannelB = \relative c {
  \voiceTwo
  g4 b c d 
  | % 2
  e d c b 
  | % 3
  c b a <fis' d > 
  | % 4
  g b a g 
  | % 5
  fis g fis e 
  | % 6
  d e d cis 
  | % 7
  b fis g a 
  | % 8
  d e d c 
  | % 9
  b c b a 
  | % 10
  g a g fis 
  | % 11
  e fis g b 
  | % 12
  d c b g 
  | % 13
  c a b c8 d 
  | % 14
  e4 d c b 
  | % 15
  a b8 c d4 d, 
  | % 16
  g1 
  | % 17
  g4 b c d 
  | % 18
  e d c b 
  | % 19
  c b a <fis' d > 
  | % 20
  g b a g 
  | % 21
  fis g fis e 
  | % 22
  d e d cis 
  | % 23
  b fis g a 
  | % 24
  d e d c 
  | % 25
  b c b a 
  | % 26
  g a g fis 
  | % 27
  e fis g b 
  | % 28
  d c b g 
  | % 29
  c a b c8 d 
  | % 30
  e4 d c b 
  | % 31
  a b8 c d4 d, 
  | % 32
  g1 
  | % 33
  g4 b c d 
  | % 34
  e d c b 
  | % 35
  c b a <fis' d > 
  | % 36
  g b a g 
  | % 37
  fis g fis e 
  | % 38
  d e d cis 
  | % 39
  b fis g a 
  | % 40
  d e d c 
  | % 41
  b c b a 
  | % 42
  g a g fis 
  | % 43
  e fis g b 
  | % 44
  d c b g 
  | % 45
  c a b c8 d 
  | % 46
  e4 d c b 
  | % 47
  a b8 c d4 d, 
  | % 48
  g1 
  | % 49
  g4 b c d 
  | % 50
  e d c b 
  | % 51
  c b a <fis' d > 
  | % 52
  g b a g 
  | % 53
  fis g fis e 
  | % 54
  d e d cis 
  | % 55
  b fis g a 
  | % 56
  d e d c 
  | % 57
  b c b a 
  | % 58
  g a g fis 
  | % 59
  e fis g b 
  | % 60
  d c b g 
  | % 61
  c a b c8 d 
  | % 62
  e4 d c b 
  | % 63
  a b8 c d4 d, 
  | % 64
  g1 
  | % 65
  g4 b c d 
  | % 66
  e d c b 
  | % 67
  c b a <fis' d > 
  | % 68
  g b a g 
  | % 69
  fis g fis e 
  | % 70
  d e d cis 
  | % 71
  b fis g a 
  | % 72
  d e d c 
  | % 73
  b c b a 
  | % 74
  g a g fis 
  | % 75
  e fis g b 
  | % 76
  d c b g 
  | % 77
  c a b c8 d 
  | % 78
  e4 d c b 
  | % 79
  a b8 c d4 d, 
  | % 80
  g1 
  | % 81
  
}

trackDchannelBvoiceB = \relative c {
  \voiceOne
  r1*2 g'2. r4*35 g2 
  | % 13
  g g 
  | % 14
  g g 
  | % 15
  r1*4 g2. r4*35 g2 
  | % 29
  g g 
  | % 30
  g g 
  | % 31
  r1*4 g2. r4*35 g2 
  | % 45
  g g 
  | % 46
  g g 
  | % 47
  r1*4 g2. r4*35 g2 
  | % 61
  g g 
  | % 62
  g g 
  | % 63
  r1*4 g2. r4*35 g2 
  | % 77
  g g 
  | % 78
  g g 
  | % 79
  
}

trackD = <<

  \clef bass
  
  \context Voice = voiceA \trackDchannelA
  \context Voice = voiceB \trackDchannelB
  \context Voice = voiceC \trackDchannelBvoiceB
>>


trackE = <<
>>


trackFchannelA = {
  
  \set Staff.instrumentName = "Digital Hymn #421"
  
}

trackF = <<
  \context Voice = voiceA \trackFchannelA
>>


trackGchannelA = {
  
  \set Staff.instrumentName = "For All the Saints"
  
}

trackG = <<
  \context Voice = voiceA \trackGchannelA
>>


\score {
  <<
    \context Staff=trackB \trackA
    \context Staff=trackB \trackB
    \context Staff=trackC \trackA
    \context Staff=trackC \trackC
    \context Staff=trackD \trackA
    \context Staff=trackD \trackD
  >>
  \layout {}
  \midi {}
}
