% Lily was here -- automatically converted by c:/Program Files (x86)/LilyPond/usr/bin/midi2ly.py from output/midi/525-hiding-in-thee.mid
\version "2.14.0"

\layout {
  \context {
    \Voice
    \remove "Note_heads_engraver"
    \consists "Completion_heads_engraver"
    \remove "Rest_engraver"
    \consists "Completion_rest_engraver"
  }
}

trackAchannelA = {


  \key f \major
    
  \set Staff.instrumentName = "Hiding in Thee"
  
  % [TEXT_EVENT] By Ira D.Sankey
  
  % [COPYRIGHT_NOTICE] Public  domain
  
  % [TEXT_EVENT] Generated by NoteWorthy Composer
  
  \tempo 4 = 125 
  

  \key f \major
  
  \time 4/4 
  
}

trackA = <<
  \context Voice = voiceA \trackAchannelA
>>


trackBchannelA = {
  
  \set Staff.instrumentName = "Unnamed-000"
  
}

trackBchannelB = \relative c {
  \voiceOne
  <f' c' >4 <f c' >2 <f bes >4 
  | % 2
  <f a > <f a >2 <c g' >4 
  | % 3
  <c f > f e d 
  | % 4
  <c e > <c f >16*11 r16 
  | % 5
  f4 <f bes >2 <f a >4 
  | % 6
  <f d' > <f c' >2 <f a >4 
  | % 7
  f <e g >2 <f a >4 
  | % 8
  <f b > <e c' >16*11 r16 
  | % 9
  <e c' >4 <f c' >2 <f bes >4 
  | % 10
  <f a > <f a >2 <c g' >4 
  | % 11
  <c f > f e d 
  | % 12
  <c e > <c f >16*11 r16 
  | % 13
  f4 <f bes >2 <f a >4 
  | % 14
  <f d' > <f c' >2 <f a >4 
  | % 15
  f <f a >2 <e a >4. <e g >8 f16*15 r16 <e g >2 <e g >4. <f a >8 
  <g bes >16*15 r16 <f a >2 <f a >4. <f bes >8 <f c' >16*11 r16 
  | % 21
  <a c >4 <a f' >2 <c e >4. <bes d >8 <a c >2 <f a >4 
  | % 23
  f <f a >2 <e a >4. <e g >8 f16*15 
}

trackBchannelBvoiceB = \relative c {
  \voiceTwo
  r4*9 bes'16*7 r16*121 bes16*7 
}

trackB = <<
  \context Voice = voiceA \trackBchannelA
  \context Voice = voiceB \trackBchannelB
  \context Voice = voiceC \trackBchannelBvoiceB
>>


trackCchannelA = {
  
  \set Staff.instrumentName = "Unnamed-001"
  
}

trackCchannelB = \relative c {
  \voiceTwo
  <f a >4 <f a >2 <f d' >4 
  | % 2
  <f c' > <f c' >2 <f bes >4 
  | % 3
  <f a > <c g' >2 <c bes' >4 
  | % 4
  <c bes' > <f a >16*11 r16 
  | % 5
  <f a >4 <f d' >2 <f c' >4 
  | % 6
  <f bes > <f a >2 <f c' >4 
  | % 7
  <a, c' > <c c' >2 <f c' >4 
  | % 8
  <e g > <c g' >16*11 r16 
  | % 9
  <c bes' >4 <f a >2 <f d' >4 
  | % 10
  <f c' > <f c' >2 <f bes >4 
  | % 11
  <f a > <c g' >2 <c bes' >4 
  | % 12
  <c bes' > <f a >16*11 r16 
  | % 13
  <f a >4 <f d' >2 <f c' >4 
  | % 14
  <f bes > <f a >2 f4 
  | % 15
  <d a' > <c c' >2 <c c' >4. <c bes' >8 <f a >16*15 r16 <c c' >2 
  <c c' >4. <c c' >8 <c c' >16*15 r16 <f c' >2 <f c' >4. f4*94/192 
  r4*2/192 <f a >16*11 r16 
  | % 21
  <f c' >4 <f c' >2 <f c' >4. <f f' >8 <f f' >2 <f c' >4 
  | % 23
  <f a >8 <d b' > <c c' >2 <c c' >4. <c bes' >8 f16*15 
}

trackCchannelBvoiceB = \relative c {
  \voiceOne
  r8*153 g'8 
}

trackC = <<

  \clef bass
  
  \context Voice = voiceA \trackCchannelA
  \context Voice = voiceB \trackCchannelB
  \context Voice = voiceC \trackCchannelBvoiceB
>>


\score {
  <<
    \context Staff=trackB \trackA
    \context Staff=trackB \trackB
    \context Staff=trackC \trackA
    \context Staff=trackC \trackC
  >>
  \layout {}
  \midi {}
}
